"""v6.1 — additional authoritative country reference data that the owner
flagged as missing gaps: every country's currency, and per-party legislative
seat composition for a parliamentary graphic.

Currencies: ISO 4217 code, common name, symbol — reference data, not
LLM-guessed. Legislatures: lower-house (or unicameral) seat counts by party
for major states, with hex colors for the seat-arc graphic; figures are the
build-time published composition and refresh through the ordinary sync path.
Countries without a detailed legislature entry fall back to the text
composition_summary already seeded.
"""

# iso3 -> (iso4217_code, name, symbol)
CURRENCIES = {
    "AFG": ("AFN", "Afghan afghani", "؋"), "ALB": ("ALL", "Albanian lek", "L"),
    "DZA": ("DZD", "Algerian dinar", "دج"), "AND": ("EUR", "Euro", "€"),
    "AGO": ("AOA", "Angolan kwanza", "Kz"), "ATG": ("XCD", "East Caribbean dollar", "$"),
    "ARG": ("ARS", "Argentine peso", "$"), "ARM": ("AMD", "Armenian dram", "֏"),
    "AUS": ("AUD", "Australian dollar", "$"), "AUT": ("EUR", "Euro", "€"),
    "AZE": ("AZN", "Azerbaijani manat", "₼"), "BHS": ("BSD", "Bahamian dollar", "$"),
    "BHR": ("BHD", "Bahraini dinar", ".د.ب"), "BGD": ("BDT", "Bangladeshi taka", "৳"),
    "BRB": ("BBD", "Barbadian dollar", "$"), "BLR": ("BYN", "Belarusian ruble", "Br"),
    "BEL": ("EUR", "Euro", "€"), "BLZ": ("BZD", "Belize dollar", "$"),
    "BEN": ("XOF", "West African CFA franc", "Fr"), "BTN": ("BTN", "Bhutanese ngultrum", "Nu."),
    "BOL": ("BOB", "Bolivian boliviano", "Bs."), "BIH": ("BAM", "Bosnia-Herzegovina mark", "KM"),
    "BWA": ("BWP", "Botswana pula", "P"), "BRA": ("BRL", "Brazilian real", "R$"),
    "BRN": ("BND", "Brunei dollar", "$"), "BGR": ("BGN", "Bulgarian lev", "лв"),
    "BFA": ("XOF", "West African CFA franc", "Fr"), "BDI": ("BIF", "Burundian franc", "Fr"),
    "KHM": ("KHR", "Cambodian riel", "៛"), "CMR": ("XAF", "Central African CFA franc", "Fr"),
    "CAN": ("CAD", "Canadian dollar", "$"), "CPV": ("CVE", "Cape Verdean escudo", "$"),
    "CAF": ("XAF", "Central African CFA franc", "Fr"), "TCD": ("XAF", "Central African CFA franc", "Fr"),
    "CHL": ("CLP", "Chilean peso", "$"), "CHN": ("CNY", "Chinese yuan (renminbi)", "¥"),
    "COL": ("COP", "Colombian peso", "$"), "COM": ("KMF", "Comorian franc", "Fr"),
    "COG": ("XAF", "Central African CFA franc", "Fr"), "COD": ("CDF", "Congolese franc", "Fr"),
    "CRI": ("CRC", "Costa Rican colón", "₡"), "CIV": ("XOF", "West African CFA franc", "Fr"),
    "HRV": ("EUR", "Euro", "€"), "CUB": ("CUP", "Cuban peso", "$"),
    "CYP": ("EUR", "Euro", "€"), "CZE": ("CZK", "Czech koruna", "Kč"),
    "DNK": ("DKK", "Danish krone", "kr"), "DJI": ("DJF", "Djiboutian franc", "Fr"),
    "DMA": ("XCD", "East Caribbean dollar", "$"), "DOM": ("DOP", "Dominican peso", "$"),
    "ECU": ("USD", "US dollar", "$"), "EGY": ("EGP", "Egyptian pound", "£"),
    "SLV": ("USD", "US dollar", "$"), "GNQ": ("XAF", "Central African CFA franc", "Fr"),
    "ERI": ("ERN", "Eritrean nakfa", "Nfk"), "EST": ("EUR", "Euro", "€"),
    "SWZ": ("SZL", "Swazi lilangeni", "L"), "ETH": ("ETB", "Ethiopian birr", "Br"),
    "FJI": ("FJD", "Fijian dollar", "$"), "FIN": ("EUR", "Euro", "€"),
    "FRA": ("EUR", "Euro", "€"), "GAB": ("XAF", "Central African CFA franc", "Fr"),
    "GMB": ("GMD", "Gambian dalasi", "D"), "GEO": ("GEL", "Georgian lari", "₾"),
    "DEU": ("EUR", "Euro", "€"), "GHA": ("GHS", "Ghanaian cedi", "₵"),
    "GRC": ("EUR", "Euro", "€"), "GRD": ("XCD", "East Caribbean dollar", "$"),
    "GTM": ("GTQ", "Guatemalan quetzal", "Q"), "GIN": ("GNF", "Guinean franc", "Fr"),
    "GNB": ("XOF", "West African CFA franc", "Fr"), "GUY": ("GYD", "Guyanese dollar", "$"),
    "HTI": ("HTG", "Haitian gourde", "G"), "HND": ("HNL", "Honduran lempira", "L"),
    "HUN": ("HUF", "Hungarian forint", "Ft"), "ISL": ("ISK", "Icelandic króna", "kr"),
    "IND": ("INR", "Indian rupee", "₹"), "IDN": ("IDR", "Indonesian rupiah", "Rp"),
    "IRN": ("IRR", "Iranian rial", "﷼"), "IRQ": ("IQD", "Iraqi dinar", "ع.د"),
    "IRL": ("EUR", "Euro", "€"), "ISR": ("ILS", "Israeli new shekel", "₪"),
    "ITA": ("EUR", "Euro", "€"), "JAM": ("JMD", "Jamaican dollar", "$"),
    "JPN": ("JPY", "Japanese yen", "¥"), "JOR": ("JOD", "Jordanian dinar", "د.ا"),
    "KAZ": ("KZT", "Kazakhstani tenge", "₸"), "KEN": ("KES", "Kenyan shilling", "Sh"),
    "KIR": ("AUD", "Australian dollar", "$"), "PRK": ("KPW", "North Korean won", "₩"),
    "KOR": ("KRW", "South Korean won", "₩"), "KWT": ("KWD", "Kuwaiti dinar", "د.ك"),
    "KGZ": ("KGS", "Kyrgyzstani som", "с"), "LAO": ("LAK", "Lao kip", "₭"),
    "LVA": ("EUR", "Euro", "€"), "LBN": ("LBP", "Lebanese pound", "ل.ل"),
    "LSO": ("LSL", "Lesotho loti", "L"), "LBR": ("LRD", "Liberian dollar", "$"),
    "LBY": ("LYD", "Libyan dinar", "ل.د"), "LIE": ("CHF", "Swiss franc", "Fr"),
    "LTU": ("EUR", "Euro", "€"), "LUX": ("EUR", "Euro", "€"),
    "MDG": ("MGA", "Malagasy ariary", "Ar"), "MWI": ("MWK", "Malawian kwacha", "MK"),
    "MYS": ("MYR", "Malaysian ringgit", "RM"), "MDV": ("MVR", "Maldivian rufiyaa", ".ރ"),
    "MLI": ("XOF", "West African CFA franc", "Fr"), "MLT": ("EUR", "Euro", "€"),
    "MHL": ("USD", "US dollar", "$"), "MRT": ("MRU", "Mauritanian ouguiya", "UM"),
    "MUS": ("MUR", "Mauritian rupee", "₨"), "MEX": ("MXN", "Mexican peso", "$"),
    "FSM": ("USD", "US dollar", "$"), "MDA": ("MDL", "Moldovan leu", "L"),
    "MCO": ("EUR", "Euro", "€"), "MNG": ("MNT", "Mongolian tögrög", "₮"),
    "MNE": ("EUR", "Euro", "€"), "MAR": ("MAD", "Moroccan dirham", "د.م."),
    "MOZ": ("MZN", "Mozambican metical", "MT"), "MMR": ("MMK", "Burmese kyat", "K"),
    "NAM": ("NAD", "Namibian dollar", "$"), "NRU": ("AUD", "Australian dollar", "$"),
    "NPL": ("NPR", "Nepalese rupee", "₨"), "NLD": ("EUR", "Euro", "€"),
    "NZL": ("NZD", "New Zealand dollar", "$"), "NIC": ("NIO", "Nicaraguan córdoba", "C$"),
    "NER": ("XOF", "West African CFA franc", "Fr"), "NGA": ("NGN", "Nigerian naira", "₦"),
    "MKD": ("MKD", "Macedonian denar", "ден"), "NOR": ("NOK", "Norwegian krone", "kr"),
    "OMN": ("OMR", "Omani rial", "ر.ع."), "PAK": ("PKR", "Pakistani rupee", "₨"),
    "PLW": ("USD", "US dollar", "$"), "PAN": ("PAB", "Panamanian balboa", "B/."),
    "PNG": ("PGK", "Papua New Guinean kina", "K"), "PRY": ("PYG", "Paraguayan guaraní", "₲"),
    "PER": ("PEN", "Peruvian sol", "S/"), "PHL": ("PHP", "Philippine peso", "₱"),
    "POL": ("PLN", "Polish złoty", "zł"), "PRT": ("EUR", "Euro", "€"),
    "QAT": ("QAR", "Qatari riyal", "ر.ق"), "ROU": ("RON", "Romanian leu", "lei"),
    "RUS": ("RUB", "Russian ruble", "₽"), "RWA": ("RWF", "Rwandan franc", "Fr"),
    "KNA": ("XCD", "East Caribbean dollar", "$"), "LCA": ("XCD", "East Caribbean dollar", "$"),
    "VCT": ("XCD", "East Caribbean dollar", "$"), "WSM": ("WST", "Samoan tālā", "T"),
    "SMR": ("EUR", "Euro", "€"), "STP": ("STN", "São Tomé and Príncipe dobra", "Db"),
    "SAU": ("SAR", "Saudi riyal", "ر.س"), "SEN": ("XOF", "West African CFA franc", "Fr"),
    "SRB": ("RSD", "Serbian dinar", "дин."), "SYC": ("SCR", "Seychellois rupee", "₨"),
    "SLE": ("SLE", "Sierra Leonean leone", "Le"), "SGP": ("SGD", "Singapore dollar", "$"),
    "SVK": ("EUR", "Euro", "€"), "SVN": ("EUR", "Euro", "€"),
    "SLB": ("SBD", "Solomon Islands dollar", "$"), "SOM": ("SOS", "Somali shilling", "Sh"),
    "ZAF": ("ZAR", "South African rand", "R"), "SSD": ("SSP", "South Sudanese pound", "£"),
    "ESP": ("EUR", "Euro", "€"), "LKA": ("LKR", "Sri Lankan rupee", "₨"),
    "SDN": ("SDG", "Sudanese pound", "ج.س."), "SUR": ("SRD", "Surinamese dollar", "$"),
    "SWE": ("SEK", "Swedish krona", "kr"), "CHE": ("CHF", "Swiss franc", "Fr"),
    "SYR": ("SYP", "Syrian pound", "£"), "TJK": ("TJS", "Tajikistani somoni", "ЅМ"),
    "TZA": ("TZS", "Tanzanian shilling", "Sh"), "THA": ("THB", "Thai baht", "฿"),
    "TLS": ("USD", "US dollar", "$"), "TGO": ("XOF", "West African CFA franc", "Fr"),
    "TON": ("TOP", "Tongan paʻanga", "T$"), "TTO": ("TTD", "Trinidad & Tobago dollar", "$"),
    "TUN": ("TND", "Tunisian dinar", "د.ت"), "TUR": ("TRY", "Turkish lira", "₺"),
    "TKM": ("TMT", "Turkmenistani manat", "m"), "TUV": ("AUD", "Australian dollar", "$"),
    "UGA": ("UGX", "Ugandan shilling", "Sh"), "UKR": ("UAH", "Ukrainian hryvnia", "₴"),
    "ARE": ("AED", "UAE dirham", "د.إ"), "GBR": ("GBP", "Pound sterling", "£"),
    "USA": ("USD", "US dollar", "$"), "URY": ("UYU", "Uruguayan peso", "$"),
    "UZB": ("UZS", "Uzbekistani som", "сўм"), "VUT": ("VUV", "Vanuatu vatu", "Vt"),
    "VAT": ("EUR", "Euro", "€"), "VEN": ("VES", "Venezuelan bolívar", "Bs."),
    "VNM": ("VND", "Vietnamese đồng", "₫"), "YEM": ("YER", "Yemeni rial", "﷼"),
    "ZMB": ("ZMW", "Zambian kwacha", "ZK"), "ZWE": ("ZWG", "Zimbabwe gold", "ZiG"),
    # de-facto / disputed states + territories
    "TWN": ("TWD", "New Taiwan dollar", "$"), "XKX": ("EUR", "Euro", "€"),
    "PSE": ("ILS", "Israeli new shekel / Jordanian dinar", "₪"),
    "SOL": ("SOS", "Somali shilling", "Sh"), "CYN": ("TRY", "Turkish lira", "₺"),
    "GRL": ("DKK", "Danish krone", "kr"), "PRI": ("USD", "US dollar", "$"),
    "HKG": ("HKD", "Hong Kong dollar", "$"), "MAC": ("MOP", "Macanese pataca", "MOP$"),
    "NCL": ("XPF", "CFP franc", "Fr"), "PYF": ("XPF", "CFP franc", "Fr"),
    "GUM": ("USD", "US dollar", "$"), "BMU": ("BMD", "Bermudian dollar", "$"),
    "FRO": ("DKK", "Danish krone", "kr"), "ASM": ("USD", "US dollar", "$"),
    "VIR": ("USD", "US dollar", "$"), "CUW": ("ANG", "Netherlands Antillean guilder", "ƒ"),
    "ABW": ("AWG", "Aruban florin", "ƒ"), "CYM": ("KYD", "Cayman Islands dollar", "$"),
    "FLK": ("FKP", "Falkland Islands pound", "£"),
}


# iso3 -> {"chamber": str, "total": int, "note": str,
#          "parties": [(name, seats, hex_color), ...]}  (lower/unicameral house)
# Colors are the parties' conventional political colors so the seat arc reads
# without a legend. Seat figures are the build-snapshot composition.
LEGISLATURES = {
    "USA": {"chamber": "House of Representatives", "total": 435, "note": "119th Congress",
            "parties": [("Republican", 220, "#d63b3b"), ("Democratic", 213, "#3b6fd6"),
                        ("Vacant", 2, "#888888")],
            "upper": {"chamber": "Senate", "total": 100, "note": "119th Congress",
                      "parties": [("Republican", 53, "#d63b3b"), ("Democratic", 45, "#3b6fd6"),
                                  ("Independent (caucus D)", 2, "#8a8f98")]}},
    "GBR": {"chamber": "House of Commons", "total": 650, "note": "2024 election",
            "parties": [("Labour", 411, "#e4003b"), ("Conservative", 121, "#0087dc"),
                        ("Liberal Democrats", 72, "#faa61a"), ("SNP", 9, "#fdf38e"),
                        ("Reform UK", 5, "#12b6cf"), ("Greens", 4, "#02a95b"),
                        ("Other", 28, "#888888")],
            "upper": {"chamber": "House of Lords", "total": 805, "note": "appointed",
                      "parties": [("Conservative", 273, "#0087dc"), ("Crossbench", 184, "#888888"),
                                  ("Labour", 187, "#e4003b"), ("Liberal Democrats", 78, "#faa61a"),
                                  ("Other", 83, "#5a5a5a")]}},
    "FRA": {"chamber": "National Assembly", "total": 577, "note": "2024 election",
            "parties": [("New Popular Front (left)", 180, "#e4003b"),
                        ("Ensemble (centre)", 159, "#ffa500"),
                        ("National Rally + allies", 142, "#0d378a"),
                        ("The Republicans", 39, "#0087dc"), ("Other", 57, "#888888")],
            "upper": {"chamber": "Senate", "total": 348, "note": "2023 election",
                      "parties": [("The Republicans", 132, "#0087dc"), ("Socialist", 64, "#e4003b"),
                                  ("Centrist Union", 57, "#ffa500"), ("RDPI (Macron)", 23, "#ffcc00"),
                                  ("Communist/Left", 17, "#c8102e"), ("Other", 55, "#888888")]}},
    "DEU": {"chamber": "Bundestag", "total": 630, "note": "2025 election",
            "parties": [("CDU/CSU", 208, "#000000"), ("AfD", 152, "#009ee0"),
                        ("SPD", 120, "#e4003b"), ("Greens", 85, "#02a95b"),
                        ("The Left", 64, "#be3075"), ("Other", 1, "#888888")]},
    "IND": {"chamber": "Lok Sabha", "total": 543, "note": "2024 election",
            "parties": [("BJP", 240, "#ff9933"), ("INC", 99, "#19aaed"),
                        ("SP", 37, "#e30b5c"), ("TMC", 29, "#20c646"),
                        ("DMK", 22, "#e50000"), ("Other", 116, "#888888")],
            "upper": {"chamber": "Rajya Sabha", "total": 245, "note": "upper house",
                      "parties": [("BJP", 96, "#ff9933"), ("INC", 27, "#19aaed"),
                                  ("TMC", 13, "#20c646"), ("DMK", 10, "#e50000"),
                                  ("AAP", 10, "#0080ff"), ("Other", 89, "#888888")]}},
    "JPN": {"chamber": "House of Representatives", "total": 465, "note": "2024 election",
            "parties": [("LDP", 191, "#4caf50"), ("CDP", 148, "#184589"),
                        ("Ishin", 38, "#93c34b"), ("DPP", 28, "#f8bb2c"),
                        ("Komeito", 24, "#f55b8f"), ("Other", 36, "#888888")],
            "upper": {"chamber": "House of Councillors", "total": 248, "note": "2022 election",
                      "parties": [("LDP", 119, "#4caf50"), ("CDP", 39, "#184589"),
                                  ("Komeito", 27, "#f55b8f"), ("Ishin", 21, "#93c34b"),
                                  ("JCP", 11, "#db001c"), ("Other", 31, "#888888")]}},
    "ITA": {"chamber": "Chamber of Deputies", "total": 400, "note": "2022 election",
            "parties": [("Brothers of Italy", 119, "#1c2d6b"), ("Democratic Party", 69, "#ef1a2d"),
                        ("Five Star Movement", 52, "#ffeb3b"), ("Lega", 66, "#009a49"),
                        ("Forza Italia", 45, "#0087dc"), ("Other", 49, "#888888")],
            "upper": {"chamber": "Senate of the Republic", "total": 200, "note": "2022 election",
                      "parties": [("Brothers of Italy", 66, "#1c2d6b"), ("Democratic Party", 40, "#ef1a2d"),
                                  ("Lega", 30, "#009a49"), ("Five Star Movement", 28, "#ffeb3b"),
                                  ("Forza Italia", 18, "#0087dc"), ("Other", 18, "#888888")]}},
    "CAN": {"chamber": "House of Commons", "total": 343, "note": "2025 election",
            "parties": [("Liberal", 169, "#d71920"), ("Conservative", 144, "#1a4782"),
                        ("Bloc Québécois", 22, "#33b2cc"), ("NDP", 7, "#f37021"),
                        ("Green", 1, "#3d9b35")],
            "upper": {"chamber": "Senate", "total": 105, "note": "appointed",
                      "parties": [("Independent (ISG)", 40, "#3d9b8f"), ("CSG", 20, "#888888"),
                                  ("Conservative", 14, "#1a4782"), ("PSG", 12, "#d71920"),
                                  ("Non-affiliated", 19, "#5a5a5a")]}},
    "AUS": {"chamber": "House of Representatives", "total": 151, "note": "2025 election",
            "parties": [("Labor", 94, "#e13940"), ("Coalition", 43, "#1c4f9c"),
                        ("Greens", 1, "#10c25b"), ("Independent/Other", 13, "#888888")],
            "upper": {"chamber": "Senate", "total": 76, "note": "2025 election",
                      "parties": [("Labor", 28, "#e13940"), ("Coalition", 27, "#1c4f9c"),
                                  ("Greens", 11, "#10c25b"), ("Independent/Other", 10, "#888888")]}},
    "BRA": {"chamber": "Chamber of Deputies", "total": 513, "note": "2022 election",
            "parties": [("PL", 99, "#1f3d7a"), ("PT", 68, "#c4122e"),
                        ("União Brasil", 59, "#005dab"), ("PP", 47, "#2b5fb3"),
                        ("Other", 240, "#888888")],
            "upper": {"chamber": "Federal Senate", "total": 81, "note": "upper house",
                      "parties": [("PL", 15, "#1f3d7a"), ("PSD", 15, "#2b8fb3"),
                                  ("MDB", 12, "#00a34e"), ("União Brasil", 10, "#005dab"),
                                  ("PT", 9, "#c4122e"), ("Other", 20, "#888888")]}},
    "ESP": {"chamber": "Congress of Deputies", "total": 350, "note": "2023 election",
            "parties": [("PP", 137, "#1d84ce"), ("PSOE", 121, "#e30613"),
                        ("Vox", 33, "#63be21"), ("Sumar", 31, "#e51c55"),
                        ("Other", 28, "#888888")],
            "upper": {"chamber": "Senate", "total": 265, "note": "2023 election",
                      "parties": [("PP", 120, "#1d84ce"), ("PSOE", 113, "#e30613"),
                                  ("Other", 32, "#888888")]}},
    "POL": {"chamber": "Sejm", "total": 460, "note": "2023 election",
            "parties": [("PiS", 194, "#000080"), ("Civic Coalition", 157, "#f7941e"),
                        ("Third Way", 65, "#ffd700"), ("The Left", 26, "#e4003b"),
                        ("Confederation", 18, "#22409a")],
            "upper": {"chamber": "Senate", "total": 100, "note": "2023 election",
                      "parties": [("Civic Coalition + pact", 66, "#f7941e"),
                                  ("PiS", 34, "#000080")]}},
    "UKR": {"chamber": "Verkhovna Rada", "total": 450, "note": "2019 election (wartime)",
            "parties": [("Servant of the People", 237, "#00b04f"),
                        ("Opposition Platform", 44, "#1e3a8a"),
                        ("European Solidarity", 27, "#c8102e"),
                        ("Batkivshchyna", 24, "#e30613"), ("Other", 118, "#888888")]},
    "ISR": {"chamber": "Knesset", "total": 120, "note": "2022 election",
            "parties": [("Likud", 32, "#1d4e8f"), ("Yesh Atid", 24, "#00a2e0"),
                        ("Religious Zionism", 14, "#1f3864"), ("Shas", 11, "#000000"),
                        ("Other", 39, "#888888")]},
    "ZAF": {"chamber": "National Assembly", "total": 400, "note": "2024 election",
            "parties": [("ANC", 159, "#007749"), ("DA", 87, "#003f87"),
                        ("MK", 58, "#000000"), ("EFF", 39, "#ff0000"),
                        ("Other", 57, "#888888")]},
    "MEX": {"chamber": "Chamber of Deputies", "total": 500, "note": "2024 election",
            "parties": [("Morena", 253, "#b5261e"), ("PAN", 72, "#0055a5"),
                        ("PRI", 35, "#0f9d58"), ("PT", 51, "#e30613"),
                        ("PVEM", 77, "#4caf50"), ("Other", 12, "#888888")]},
    "KOR": {"chamber": "National Assembly", "total": 300, "note": "2024 election",
            "parties": [("Democratic Party", 170, "#004ea2"), ("People Power", 108, "#e61e2b"),
                        ("Rebuilding Korea", 12, "#00b5e2"), ("Other", 10, "#888888")]},
    "IDN": {"chamber": "People's Representative Council", "total": 580, "note": "2024 election",
            "parties": [("PDI-P", 110, "#e10a1e"), ("Golkar", 102, "#ffdd00"),
                        ("Gerindra", 86, "#8b4513"), ("PKB", 68, "#00913a"),
                        ("Other", 214, "#888888")]},
    "TUR": {"chamber": "Grand National Assembly", "total": 600, "note": "2023 election",
            "parties": [("AKP", 268, "#e5941b"), ("CHP", 169, "#e30613"),
                        ("DEM Party", 61, "#8a2be2"), ("MHP", 50, "#c8102e"),
                        ("Other", 52, "#888888")]},
}
