"""v3 §13-23 — geopolitical entity layer seed data.

Slow-changing reference facts, seeded so the entity layer is functional
from first launch and refreshed on schedule from Wikidata / World Bank
(sync.py). Leadership rows carry last_refreshed_at = NULL until the first
successful Wikidata sync — the UI can therefore always tell seed data
("as shipped") from synced data. Chokepoints, contested territories, and
critical infrastructure are a manually-curated list per §17 — there is no
clean free API for 'strategically significant places'.
"""

# (iso3, name, capital, region, government_type, cap_lat, cap_lon)
COUNTRIES = [
    ("USA", "United States", "Washington, D.C.", "North America", "federal presidential republic", 38.9, -77.0),
    ("CHN", "China", "Beijing", "East Asia", "one-party socialist republic", 39.9, 116.4),
    ("RUS", "Russia", "Moscow", "Eastern Europe / North Asia", "federal semi-presidential republic", 55.8, 37.6),
    ("GBR", "United Kingdom", "London", "Western Europe", "parliamentary constitutional monarchy", 51.5, -0.1),
    ("FRA", "France", "Paris", "Western Europe", "semi-presidential republic", 48.9, 2.4),
    ("DEU", "Germany", "Berlin", "Western Europe", "federal parliamentary republic", 52.5, 13.4),
    ("JPN", "Japan", "Tokyo", "East Asia", "parliamentary constitutional monarchy", 35.7, 139.7),
    ("IND", "India", "New Delhi", "South Asia", "federal parliamentary republic", 28.6, 77.2),
    ("BRA", "Brazil", "Brasília", "South America", "federal presidential republic", -15.8, -47.9),
    ("ITA", "Italy", "Rome", "Southern Europe", "parliamentary republic", 41.9, 12.5),
    ("CAN", "Canada", "Ottawa", "North America", "federal parliamentary monarchy", 45.4, -75.7),
    ("KOR", "South Korea", "Seoul", "East Asia", "presidential republic", 37.6, 127.0),
    ("AUS", "Australia", "Canberra", "Oceania", "federal parliamentary monarchy", -35.3, 149.1),
    ("ESP", "Spain", "Madrid", "Southern Europe", "parliamentary constitutional monarchy", 40.4, -3.7),
    ("MEX", "Mexico", "Mexico City", "North America", "federal presidential republic", 19.4, -99.1),
    ("IDN", "Indonesia", "Jakarta", "Southeast Asia", "presidential republic", -6.2, 106.8),
    ("TUR", "Turkey", "Ankara", "Western Asia", "presidential republic", 39.9, 32.9),
    ("SAU", "Saudi Arabia", "Riyadh", "Middle East", "absolute monarchy", 24.7, 46.7),
    ("IRN", "Iran", "Tehran", "Middle East", "theocratic republic", 35.7, 51.4),
    ("ISR", "Israel", "Jerusalem", "Middle East", "parliamentary republic", 31.8, 35.2),
    ("EGY", "Egypt", "Cairo", "North Africa", "presidential republic", 30.0, 31.2),
    ("ZAF", "South Africa", "Pretoria", "Southern Africa", "parliamentary republic", -25.7, 28.2),
    ("NGA", "Nigeria", "Abuja", "West Africa", "federal presidential republic", 9.1, 7.5),
    ("ETH", "Ethiopia", "Addis Ababa", "East Africa", "federal parliamentary republic", 9.0, 38.7),
    ("KEN", "Kenya", "Nairobi", "East Africa", "presidential republic", -1.3, 36.8),
    ("UKR", "Ukraine", "Kyiv", "Eastern Europe", "semi-presidential republic", 50.5, 30.5),
    ("POL", "Poland", "Warsaw", "Central Europe", "parliamentary republic", 52.2, 21.0),
    ("NLD", "Netherlands", "Amsterdam", "Western Europe", "parliamentary constitutional monarchy", 52.4, 4.9),
    ("SWE", "Sweden", "Stockholm", "Northern Europe", "parliamentary constitutional monarchy", 59.3, 18.1),
    ("NOR", "Norway", "Oslo", "Northern Europe", "parliamentary constitutional monarchy", 59.9, 10.8),
    ("FIN", "Finland", "Helsinki", "Northern Europe", "parliamentary republic", 60.2, 24.9),
    ("CHE", "Switzerland", "Bern", "Western Europe", "federal directorial republic", 46.9, 7.4),
    ("GRC", "Greece", "Athens", "Southern Europe", "parliamentary republic", 38.0, 23.7),
    ("PRT", "Portugal", "Lisbon", "Southern Europe", "semi-presidential republic", 38.7, -9.1),
    ("ARG", "Argentina", "Buenos Aires", "South America", "federal presidential republic", -34.6, -58.4),
    ("CHL", "Chile", "Santiago", "South America", "presidential republic", -33.4, -70.7),
    ("COL", "Colombia", "Bogotá", "South America", "presidential republic", 4.7, -74.1),
    ("VEN", "Venezuela", "Caracas", "South America", "presidential republic", 10.5, -66.9),
    ("PAK", "Pakistan", "Islamabad", "South Asia", "federal parliamentary republic", 33.7, 73.1),
    ("BGD", "Bangladesh", "Dhaka", "South Asia", "parliamentary republic", 23.8, 90.4),
    ("VNM", "Vietnam", "Hanoi", "Southeast Asia", "one-party socialist republic", 21.0, 105.9),
    ("THA", "Thailand", "Bangkok", "Southeast Asia", "parliamentary constitutional monarchy", 13.8, 100.5),
    ("PHL", "Philippines", "Manila", "Southeast Asia", "presidential republic", 14.6, 121.0),
    ("MYS", "Malaysia", "Kuala Lumpur", "Southeast Asia", "federal parliamentary monarchy", 3.1, 101.7),
    ("SGP", "Singapore", "Singapore", "Southeast Asia", "parliamentary republic", 1.4, 103.8),
    ("TWN", "Taiwan", "Taipei", "East Asia", "semi-presidential republic", 25.0, 121.6),
    ("PRK", "North Korea", "Pyongyang", "East Asia", "one-party state", 39.0, 125.8),
    ("ARE", "United Arab Emirates", "Abu Dhabi", "Middle East", "federal monarchy", 24.5, 54.4),
    ("QAT", "Qatar", "Doha", "Middle East", "absolute monarchy", 25.3, 51.5),
    ("IRQ", "Iraq", "Baghdad", "Middle East", "federal parliamentary republic", 33.3, 44.4),
    ("SYR", "Syria", "Damascus", "Middle East", "transitional government", 33.5, 36.3),
    ("LBN", "Lebanon", "Beirut", "Middle East", "parliamentary republic", 33.9, 35.5),
    ("JOR", "Jordan", "Amman", "Middle East", "constitutional monarchy", 31.9, 35.9),
    ("YEM", "Yemen", "Sana'a", "Middle East", "contested government", 15.4, 44.2),
    ("AFG", "Afghanistan", "Kabul", "South Asia", "de facto theocratic emirate", 34.5, 69.2),
    ("MMR", "Myanmar", "Naypyidaw", "Southeast Asia", "military junta", 19.7, 96.1),
    ("SDN", "Sudan", "Khartoum", "North Africa", "contested military government", 15.6, 32.5),
    ("SSD", "South Sudan", "Juba", "East Africa", "presidential republic", 4.9, 31.6),
    ("COD", "DR Congo", "Kinshasa", "Central Africa", "semi-presidential republic", -4.3, 15.3),
    ("MLI", "Mali", "Bamako", "West Africa", "military transitional government", 12.6, -8.0),
    ("NER", "Niger", "Niamey", "West Africa", "military transitional government", 13.5, 2.1),
    ("BFA", "Burkina Faso", "Ouagadougou", "West Africa", "military transitional government", 12.4, -1.5),
    ("SOM", "Somalia", "Mogadishu", "East Africa", "federal parliamentary republic", 2.0, 45.3),
    ("LBY", "Libya", "Tripoli", "North Africa", "divided government", 32.9, 13.2),
    ("DZA", "Algeria", "Algiers", "North Africa", "presidential republic", 36.8, 3.1),
    ("MAR", "Morocco", "Rabat", "North Africa", "constitutional monarchy", 34.0, -6.8),
    ("CUB", "Cuba", "Havana", "Caribbean", "one-party socialist republic", 23.1, -82.4),
    ("BLR", "Belarus", "Minsk", "Eastern Europe", "presidential republic", 53.9, 27.6),
    ("KAZ", "Kazakhstan", "Astana", "Central Asia", "presidential republic", 51.2, 71.4),
    ("AZE", "Azerbaijan", "Baku", "Caucasus", "presidential republic", 40.4, 49.9),
    ("ARM", "Armenia", "Yerevan", "Caucasus", "parliamentary republic", 40.2, 44.5),
    ("GEO", "Georgia", "Tbilisi", "Caucasus", "parliamentary republic", 41.7, 44.8),
    ("SRB", "Serbia", "Belgrade", "Southeastern Europe", "parliamentary republic", 44.8, 20.5),
    ("HUN", "Hungary", "Budapest", "Central Europe", "parliamentary republic", 47.5, 19.0),
    ("CZE", "Czech Republic", "Prague", "Central Europe", "parliamentary republic", 50.1, 14.4),
    ("ROU", "Romania", "Bucharest", "Southeastern Europe", "semi-presidential republic", 44.4, 26.1),
    ("NZL", "New Zealand", "Wellington", "Oceania", "parliamentary constitutional monarchy", -41.3, 174.8),
]

# (iso3, role, name, party, since) — SEED values as of the build snapshot;
# last_refreshed_at stays NULL until a Wikidata sync confirms/updates them.
LEADERSHIP = [
    ("USA", "head_of_state", "Donald Trump", "Republican Party", "2025-01-20"),
    ("USA", "head_of_government", "Donald Trump", "Republican Party", "2025-01-20"),
    ("CHN", "head_of_state", "Xi Jinping", "Communist Party of China", "2013-03-14"),
    ("CHN", "head_of_government", "Li Qiang", "Communist Party of China", "2023-03-11"),
    ("RUS", "head_of_state", "Vladimir Putin", "Independent", "2012-05-07"),
    ("RUS", "head_of_government", "Mikhail Mishustin", "Independent", "2020-01-16"),
    ("GBR", "head_of_state", "King Charles III", None, "2022-09-08"),
    ("GBR", "head_of_government", "Keir Starmer", "Labour Party", "2024-07-05"),
    ("FRA", "head_of_state", "Emmanuel Macron", "Renaissance", "2017-05-14"),
    ("DEU", "head_of_government", "Friedrich Merz", "CDU", "2025-05-06"),
    ("JPN", "head_of_government", "Sanae Takaichi", "Liberal Democratic Party", "2025-10-21"),
    ("IND", "head_of_government", "Narendra Modi", "Bharatiya Janata Party", "2014-05-26"),
    ("BRA", "head_of_state", "Luiz Inácio Lula da Silva", "Workers' Party", "2023-01-01"),
    ("ITA", "head_of_government", "Giorgia Meloni", "Brothers of Italy", "2022-10-22"),
    ("CAN", "head_of_government", "Mark Carney", "Liberal Party", "2025-03-14"),
    ("KOR", "head_of_state", "Lee Jae-myung", "Democratic Party", "2025-06-04"),
    ("TUR", "head_of_state", "Recep Tayyip Erdoğan", "AKP", "2014-08-28"),
    ("SAU", "head_of_state", "King Salman", None, "2015-01-23"),
    # v5 §15 — Ali Khamenei assassinated 2026-02-28 during the 2026 Iran war;
    # Mojtaba Khamenei confirmed Supreme Leader 2026-03-09. The real fix is
    # the weekly Wikidata sync + staleness flag (sync.py), this corrects the seed.
    ("IRN", "head_of_state", "Mojtaba Khamenei (Supreme Leader)", None, "2026-03-09"),
    ("ISR", "head_of_government", "Benjamin Netanyahu", "Likud", "2022-12-29"),
    ("EGY", "head_of_state", "Abdel Fattah el-Sisi", None, "2014-06-08"),
    ("UKR", "head_of_state", "Volodymyr Zelenskyy", "Servant of the People", "2019-05-20"),
    ("MEX", "head_of_state", "Claudia Sheinbaum", "Morena", "2024-10-01"),
    ("ARG", "head_of_state", "Javier Milei", "La Libertad Avanza", "2023-12-10"),
    ("TWN", "head_of_state", "Lai Ching-te", "Democratic Progressive Party", "2024-05-20"),
    ("PRK", "head_of_state", "Kim Jong Un", "Workers' Party of Korea", "2011-12-17"),
    # v6 §21/§15 — the Taliban is Afghanistan's governing authority as of
    # 2026, not a non-state actor: reclassified out of non_state_actors and
    # populated as AFG's de-facto leadership (fixes the empty-Afghanistan-
    # profile case; countries.status='de_facto' carries the recognition nuance)
    ("AFG", "head_of_state", "Hibatullah Akhundzada (Supreme Leader)", "Taliban", "2021-08-15"),
    ("AFG", "head_of_government", "Mohammad Hassan Akhund (Acting PM)", "Taliban", "2021-09-07"),
]

# (name, type, founded, description, [member iso3...])
# v4 §5.1 — rosters are COMPLETE (the v3 hand-transcribed subsets silently
# dropped members: NATO was missing the Baltics + 7 others, ASEAN was
# missing Laos/Cambodia/Brunei). Kept in sync by the Wikidata membership
# sync (sync.py); these seeds are the full lists as of the build snapshot.
ALLIANCES = [
    ("NATO", "military", "1949-04-04", "North Atlantic Treaty Organization — collective defense alliance.",
     ["USA", "CAN", "GBR", "FRA", "DEU", "ITA", "ESP", "PRT", "NLD", "BEL", "LUX", "DNK",
      "NOR", "ISL", "POL", "CZE", "SVK", "HUN", "ROU", "BGR", "GRC", "TUR", "ALB", "HRV",
      "SVN", "MNE", "MKD", "LTU", "LVA", "EST", "FIN", "SWE"]),
    ("European Union", "economic", "1993-11-01", "Political and economic union of European states.",
     ["AUT", "BEL", "BGR", "HRV", "CYP", "CZE", "DNK", "EST", "FIN", "FRA", "DEU", "GRC",
      "HUN", "IRL", "ITA", "LVA", "LTU", "LUX", "MLT", "NLD", "POL", "PRT", "ROU", "SVK",
      "SVN", "ESP", "SWE"]),
    ("BRICS", "economic", "2009-06-16", "Bloc of major emerging economies.",
     ["BRA", "RUS", "IND", "CHN", "ZAF", "EGY", "ETH", "IRN", "ARE", "SAU", "IDN"]),
    ("OPEC", "economic", "1960-09-14", "Organization of the Petroleum Exporting Countries — oil production coordination.",
     ["SAU","IRN","IRQ","KWT","ARE","VEN","NGA","DZA","LBY","AGO","COG","GAB","GNQ"]),
    ("Mercosur", "economic", "1991-03-26", "South American common market.",
     ["BRA","ARG","URY","PRY","BOL"]),
    ("G7", "economic", "1975-11-15", "Group of Seven major advanced economies.",
     ["USA","GBR","FRA","DEU","ITA","JPN","CAN"]),
    ("Five Eyes", "military", "1946-03-05", "UKUSA signals-intelligence sharing alliance.",
     ["USA","GBR","CAN","AUS","NZL"]),
    ("QUAD", "military", "2007-05-25", "Quadrilateral Security Dialogue — Indo-Pacific strategic forum.",
     ["USA","JPN","IND","AUS"]),
    ("AUKUS", "military", "2021-09-15", "Australia–UK–US security pact (submarines, advanced tech).",
     ["AUS","GBR","USA"]),
    ("OECD", "economic", "1961-09-30", "Organisation for Economic Co-operation and Development.",
     ["USA","GBR","FRA","DEU","ITA","JPN","CAN","AUS","KOR","MEX","TUR","POL","NLD","ESP","CHE","SWE","NOR","DNK","FIN","AUT","BEL","PRT","GRC","IRL","CZE","HUN","SVK","SVN","EST","LVA","LTU","LUX","ISL","NZL","CHL","COL","CRI","ISR"]),
    # v6 §7 — Timor-Leste admitted as ASEAN's 11th member (2025 accession);
    # the Wikidata membership sync keeps this fresh, this fixes the seed
    ("ASEAN", "regional", "1967-08-08", "Association of Southeast Asian Nations.",
     ["IDN", "THA", "VNM", "PHL", "MYS", "SGP", "MMR", "LAO", "KHM", "BRN", "TLS"]),
    ("CSTO", "military", "1992-05-15", "Collective Security Treaty Organization (Russia-led).",
     ["RUS", "BLR", "KAZ", "KGZ", "TJK", "ARM"]),
    ("OPEC", "economic", "1960-09-14", "Organization of the Petroleum Exporting Countries.",
     ["SAU", "IRN", "IRQ", "KWT", "ARE", "VEN", "NGA", "DZA", "LBY", "COG", "GNQ", "GAB"]),
    ("African Union", "regional", "2002-07-09", "Continental union of African states.",
     ["DZA", "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COM", "COG",
      "COD", "CIV", "DJI", "EGY", "GNQ", "ERI", "SWZ", "ETH", "GAB", "GMB", "GHA", "GIN",
      "GNB", "KEN", "LSO", "LBR", "LBY", "MDG", "MWI", "MLI", "MRT", "MUS", "MAR", "MOZ",
      "NAM", "NER", "NGA", "RWA", "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD", "SDN",
      "TZA", "TGO", "TUN", "UGA", "ZMB", "ZWE"]),
    ("G7", "political", "1975-11-15", "Group of Seven major advanced economies.",
     ["USA", "GBR", "FRA", "DEU", "ITA", "JPN", "CAN"]),
    # --- v6 §7 — regional cooperation orgs that function as real geopolitical
    # forces (inclusion bar is exactly that, not Western media coverage) ---
    ("SCO", "regional", "2001-06-15",
     "Shanghai Cooperation Organisation — Eurasian security and economic bloc.",
     ["CHN", "IND", "KAZ", "KGZ", "PAK", "RUS", "TJK", "UZB", "IRN", "BLR"]),
    ("GCC", "regional", "1981-05-25",
     "Gulf Cooperation Council — political and economic union of Gulf Arab states.",
     ["SAU", "ARE", "KWT", "QAT", "BHR", "OMN"]),
    ("Arab League", "political", "1945-03-22",
     "League of Arab States — regional organization of the Arab world.",
     ["DZA", "BHR", "COM", "DJI", "EGY", "IRQ", "JOR", "KWT", "LBN", "LBY",
      "MRT", "MAR", "OMN", "PSE", "QAT", "SAU", "SOM", "SDN", "SYR", "TUN",
      "ARE", "YEM"]),
    ("ECOWAS", "regional", "1975-05-28",
     "Economic Community of West African States (Mali, Burkina Faso and Niger"
     " withdrew January 2025 to form the AES).",
     ["BEN", "CPV", "CIV", "GMB", "GHA", "GIN", "GNB", "LBR", "NGA", "SEN",
      "SLE", "TGO"]),
    ("Alliance of Sahel States", "military", "2023-09-16",
     "AES — confederation of the Sahel junta governments after leaving ECOWAS.",
     ["MLI", "BFA", "NER"]),
]

# (name, region, started, status, summary, [(party_type, ref, role, side)...])
# refs: iso3 for countries, NSA name for non-state actors. v6 §8: side 'a'/'b'
# groups parties for War Mode's one-color-per-side rendering; mediators NULL.
CONFLICTS = [
    ("Russia–Ukraine War", "Eastern Europe", "2022-02-24", "active",
     "Full-scale war following Russia's 2022 invasion of Ukraine; front lines, strikes and "
     "negotiations tracked via ingested coverage.",
     # v6.1 — fuller backer roster on both sides (owner: show EU/Canada/NATO
     # supporters of Ukraine, and Russia's backers). Belligerents keep side
     # a/b; backers share their side's color but list separately.
     [("country", "RUS", "belligerent", "a"), ("country", "UKR", "belligerent", "b"),
      # Ukraine's backers (side b)
      ("country", "USA", "backer", "b"), ("country", "DEU", "backer", "b"),
      ("country", "GBR", "backer", "b"), ("country", "FRA", "backer", "b"),
      ("country", "POL", "backer", "b"), ("country", "CAN", "backer", "b"),
      ("country", "NLD", "backer", "b"), ("country", "ITA", "backer", "b"),
      # Russia's backers (side a)
      ("country", "BLR", "backer", "a"), ("country", "PRK", "backer", "a"),
      ("country", "IRN", "backer", "a")]),
    ("Israel–Palestine Conflict", "Middle East", "2023-10-07", "active",
     "Conflict between Israel and Palestinian armed groups centered on Gaza, with regional "
     "spillover; ceasefire phases tracked via ingested coverage.",
     [("country", "ISR", "belligerent", "a"), ("non_state_actor", "Hamas", "belligerent", "b"),
      ("non_state_actor", "Hezbollah", "belligerent", "b"), ("country", "EGY", "mediator", None),
      ("country", "QAT", "mediator", None), ("country", "USA", "mediator", None)]),
    ("Sudan Civil War", "North Africa", "2023-04-15", "active",
     "War between the Sudanese Armed Forces and the Rapid Support Forces, with severe "
     "humanitarian consequences.",
     [("country", "SDN", "belligerent", "a"),
      ("non_state_actor", "Rapid Support Forces", "belligerent", "b")]),
    ("Myanmar Civil War", "Southeast Asia", "2021-02-01", "active",
     "Armed conflict between the military junta and resistance forces following the 2021 coup.",
     [("country", "MMR", "belligerent", "a"),
      ("non_state_actor", "People's Defence Forces (Myanmar)", "belligerent", "b")]),
    ("Sahel Insurgency", "West Africa", "2012-01-16", "active",
     "Long-running jihadist insurgency across Mali, Niger and Burkina Faso.",
     [("country", "MLI", "belligerent", "a"), ("country", "NER", "belligerent", "a"),
      ("country", "BFA", "belligerent", "a"),
      ("non_state_actor", "JNIM (al-Qaeda in the Sahel)", "belligerent", "b"),
      ("non_state_actor", "Islamic State Sahel Province", "belligerent", "b")]),
    ("DRC–M23 Conflict", "Central Africa", "2022-03-28", "active",
     "Renewed conflict in eastern DR Congo between government forces and the M23 movement.",
     [("country", "COD", "belligerent", "a"),
      ("non_state_actor", "M23 Movement", "belligerent", "b")]),
    ("U.S.–Iran War", "Middle East", "2025-06-13", "ceasefire",
     "Direct U.S.–Israeli–Iranian conflict of June 2025 (strikes on Iranian nuclear "
     "sites, Iranian missile retaliation), followed by a fragile ceasefire and an "
     "ongoing confrontation tracked via ingested coverage.",
     [("country", "USA", "belligerent", "a"), ("country", "ISR", "belligerent", "a"),
      ("country", "IRN", "belligerent", "b")]),
    # ---- v6.6 — PAST conflicts (status resolved; listed under Past conflicts) ----
    ("Gulf Wars (1990–2011)", "Middle East", "1990-08-02", "resolved",
     "Broader conflict grouping the 1990–91 Gulf War (Iraqi invasion of Kuwait and "
     "coalition Desert Storm) and the 2003–2011 Iraq War (invasion, insurgency, "
     "withdrawal).",
     [("country", "IRQ", "belligerent", "a"), ("country", "USA", "belligerent", "b"),
      ("country", "GBR", "belligerent", "b"), ("country", "KWT", "belligerent", "b")]),
    ("War in Afghanistan (2001–2021)", "Central Asia", "2001-10-07", "resolved",
     "U.S./NATO campaign against the Taliban and al-Qaeda following 9/11, ending with "
     "the 2021 withdrawal and Taliban takeover.",
     [("country", "USA", "belligerent", "a"), ("country", "GBR", "belligerent", "a"),
      ("country", "AFG", "belligerent", "a"),
      ("non_state_actor", "Taliban", "belligerent", "b")]),
    ("India–Pakistan Wars", "South Asia", "1947-10-22", "resolved",
     "Broader conflict grouping the 1947, 1965, 1971 and 1999 (Kargil) wars and the "
     "May 2025 four-day conflict (Operation Sindoor) between India and Pakistan.",
     [("country", "IND", "belligerent", "a"), ("country", "PAK", "belligerent", "b")]),
    ("Armenia–Azerbaijan Conflict", "Caucasus", "1988-02-20", "resolved",
     "The First (1988–94) and Second (2020) Nagorno-Karabakh wars and the 2023 "
     "Azerbaijani offensive; Armenia now recognizes Azerbaijani control of Karabakh.",
     [("country", "ARM", "belligerent", "a"), ("country", "AZE", "belligerent", "b")]),
]

# v6 §8 — War Mode sub-national factions: minor factions and internal control
# areas that only render inside a conflict's dedicated layout, never on the
# global map. (conflict_name, faction_name, side, [ [lon,lat]... ] ring|None)
CONFLICT_SUBFACTIONS = [
    ("Sahel Insurgency", "Azawad / Tuareg-controlled area (CSP-DPA)", "b",
     [[-3.5, 20.0], [4.2, 19.8], [1.5, 15.8], [-3.0, 16.2], [-3.5, 20.0]]),
    ("Sahel Insurgency", "Wagner/Africa Corps deployment zone", "a",
     [[-8.0, 15.5], [-2.0, 15.0], [-2.5, 12.8], [-7.5, 13.2], [-8.0, 15.5]]),
    # v6.1.1 — refined to trace the actual front line + the Crimea peninsula
    # (approx. control, not a rectangle): Luhansk in the NE, down the Donetsk/
    # Zaporizhzhia front, along the Dnipro to Kherson, and the Crimea neck.
    ("Russia–Ukraine War", "Russian-controlled territory (approx.)", "a",
     [[38.2, 49.9], [40.1, 49.6], [40.2, 48.3], [38.6, 47.9], [37.6, 47.6],
      [36.4, 47.4], [35.6, 47.3], [34.8, 46.9], [33.6, 46.7], [32.5, 46.3],
      [33.6, 46.2], [33.7, 45.9], [35.0, 45.3], [36.0, 45.4], [36.6, 45.3],
      [35.4, 44.4], [33.9, 44.4], [32.5, 45.3], [32.7, 46.0], [33.4, 46.6],
      [34.4, 47.6], [36.2, 48.2], [37.3, 48.6], [38.2, 49.9]]),
    ("Russia–Ukraine War", "Contested front-line zone", "b",
     [[36.8, 48.3], [37.9, 48.5], [38.3, 47.8], [37.2, 47.5], [36.5, 47.9],
      [36.8, 48.3]]),
    ("Myanmar Civil War", "Arakan Army-controlled Rakhine", "b",
     [[92.3, 21.4], [94.9, 20.9], [94.3, 17.9], [92.6, 19.6], [92.3, 21.4]]),
    ("Myanmar Civil War", "Kachin Independence Army zone", "b",
     [[96.2, 27.6], [98.7, 27.0], [97.9, 24.6], [96.4, 25.3], [96.2, 27.6]]),
    ("Sudan Civil War", "SPLM-N al-Hilu (Nuba Mountains)", None,
     [[29.3, 12.3], [31.4, 12.0], [30.9, 10.4], [29.6, 10.8], [29.3, 12.3]]),
    ("DRC–M23 Conflict", "Wazalendo militia areas", "a",
     [[28.4, -0.5], [29.3, -0.6], [29.1, -1.7], [28.5, -1.5], [28.4, -0.5]]),
]

# (name, actor_type, region, affiliated_state_iso3, active_since, description)
NON_STATE_ACTORS = [
    ("Hamas", "militant", "Middle East", None, "1987-12-01",
     "Palestinian Islamist political and militant organization governing Gaza; party to the "
     "Israel-Palestine conflict."),
    ("Hezbollah", "militant", "Middle East", "IRN", "1985-02-16",
     "Lebanese Shia political party and militant group; publicly reported Iranian backing."),
    ("Houthi Movement (Ansar Allah)", "militant", "Middle East", "IRN", "1994-06-01",
     "Yemeni armed movement controlling much of northwest Yemen; Red Sea shipping attacks "
     "widely reported."),
    ("JNIM (al-Qaeda in the Sahel)", "terrorist", "West Africa", None, "2017-03-02",
     "Jama'at Nasr al-Islam wal Muslimin — al-Qaeda-aligned coalition operating across the Sahel."),
    ("Islamic State Sahel Province", "terrorist", "West Africa", None, "2015-05-13",
     "Islamic State affiliate active in the tri-border Mali/Niger/Burkina Faso region."),
    ("Rapid Support Forces", "militant", "North Africa", None, "2013-06-01",
     "Sudanese paramilitary force; principal belligerent in the Sudan civil war."),
    ("M23 Movement", "insurgent", "Central Africa", None, "2012-04-04",
     "Rebel military group operating in eastern DR Congo."),
    ("People's Defence Forces (Myanmar)", "insurgent", "Southeast Asia", None, "2021-05-05",
     "Armed wing of Myanmar's National Unity Government, formed after the 2021 coup."),
    # Taliban removed v6 §21 — reclassified as Afghanistan's governing
    # authority (see NSA_GOVERNING_RECLASSIFICATIONS + AFG leadership rows)
]

# (name, category, lat, lon, description)
MARKED_LOCATIONS = [
    ("Strait of Hormuz", "strategic_chokepoint", 26.6, 56.25,
     "Roughly a fifth of global oil transits this strait between the Persian Gulf and open ocean."),
    ("Suez Canal", "strategic_chokepoint", 30.45, 32.35,
     "Primary Europe–Asia shipping route; ~12% of global trade."),
    ("Strait of Malacca", "strategic_chokepoint", 1.7, 101.0,
     "Shortest sea route between the Indian and Pacific Oceans; heaviest tanker traffic on earth."),
    ("Taiwan Strait", "strategic_chokepoint", 24.6, 119.5,
     "Waterway separating Taiwan from mainland China; critical semiconductor supply-chain corridor."),
    ("Bab el-Mandeb", "strategic_chokepoint", 12.58, 43.33,
     "Red Sea southern gate; Houthi attacks have repeatedly disrupted transits."),
    ("Bosporus Strait", "strategic_chokepoint", 41.1, 29.05,
     "Black Sea grain and energy exports pass through this Turkish strait."),
    ("Panama Canal", "strategic_chokepoint", 9.1, -79.7,
     "Interoceanic shortcut handling ~5% of world maritime trade; drought-sensitive."),
    ("Gibraltar Strait", "strategic_chokepoint", 35.95, -5.6,
     "Atlantic–Mediterranean gate."),
    ("Kerch Strait", "strategic_chokepoint", 45.25, 36.6,
     "Link between the Black Sea and the Sea of Azov; contested since 2014."),
    ("Northern Sea Route", "strategic_chokepoint", 74.0, 100.0,
     "Arctic shipping lane opening with ice retreat; Russia claims transit control."),
    ("Kashmir (Line of Control)", "contested_territory", 34.1, 74.8,
     "Disputed between India and Pakistan since 1947."),
    ("South China Sea (Spratlys)", "contested_territory", 10.0, 114.0,
     "Overlapping claims by six parties; militarized artificial islands."),
    ("Golan Heights", "contested_territory", 33.0, 35.75,
     "Israeli-occupied territory claimed by Syria."),
    ("Western Sahara", "contested_territory", 24.5, -13.0,
     "Non-self-governing territory disputed between Morocco and the Polisario Front."),
    ("Nagorno-Karabakh", "contested_territory", 39.8, 46.75,
     "Historically contested between Armenia and Azerbaijan."),
    ("TSMC Hsinchu Fabs", "semiconductor_fab", 24.77, 121.0,
     "The world's most advanced logic-chip fabrication cluster."),
    ("TSMC Tainan (Fab 18)", "semiconductor_fab", 23.1, 120.27,
     "Leading-edge 3nm/5nm production site."),
    ("Samsung Pyeongtaek", "semiconductor_fab", 37.0, 127.06,
     "One of the largest memory-chip fabrication complexes."),
    ("Bayan Obo Mine", "rare_earth_site", 41.77, 109.97,
     "China's dominant rare-earth deposit — the largest known globally."),
    ("Mount Weld Mine", "rare_earth_site", -28.86, 122.55,
     "Australia's principal rare-earth mine (Lynas)."),
    ("Mountain Pass Mine", "rare_earth_site", 35.48, -115.53,
     "The only operating US rare-earth mine."),
    ("TAT-14 / Bude Landing", "undersea_cable", 50.83, -4.55,
     "Major transatlantic cable landing cluster in Cornwall, UK."),
    ("Marseille Cable Hub", "undersea_cable", 43.3, 5.35,
     "Mediterranean landing hub connecting Europe to Asia and Africa."),
    ("Egypt Cable Corridor", "undersea_cable", 30.05, 31.25,
     "Terrestrial crossing where most Europe–Asia cables funnel through Egypt."),
    ("Nord Stream Terminus", "energy_pipeline", 54.14, 13.64,
     "Baltic gas pipeline landfall at Lubmin, Germany; sabotaged 2022."),
    ("Druzhba Pipeline Hub", "energy_pipeline", 52.2, 24.0,
     "One of the world's longest oil pipeline networks, Russia to Central Europe."),
    ("Sabine Pass LNG", "lng_terminal", 29.75, -93.87,
     "The largest US LNG export terminal."),
    ("Ras Laffan LNG", "lng_terminal", 25.9, 51.53,
     "Qatar's LNG mega-terminal — the world's largest export facility."),
]

# (name, org_type, mandate, hq, founded)
ORGANIZATIONS = [
    ("United Nations", "intergovernmental",
     "Maintain international peace and security, develop friendly relations among nations.",
     "New York, USA", "1945-10-24"),
    ("World Health Organization", "health",
     "Direct and coordinate international health within the UN system.",
     "Geneva, Switzerland", "1948-04-07"),
    ("World Trade Organization", "intergovernmental",
     "Regulate and facilitate international trade.", "Geneva, Switzerland", "1995-01-01"),
    ("International Monetary Fund", "financial",
     "Foster global monetary cooperation and financial stability.",
     "Washington, D.C., USA", "1944-07-22"),
    ("World Bank", "financial",
     "Provide loans and grants for development projects.", "Washington, D.C., USA", "1944-07-01"),
    ("International Criminal Court", "judicial",
     "Prosecute individuals for genocide, war crimes, crimes against humanity and aggression.",
     "The Hague, Netherlands", "2002-07-01"),
    ("International Court of Justice", "judicial",
     "Settle legal disputes between states; the UN's principal judicial organ.",
     "The Hague, Netherlands", "1945-06-26"),
]

# (name, treaty_type, signed, status, summary, [(iso3, ratified)...])
TREATIES = [
    ("Treaty on the Non-Proliferation of Nuclear Weapons (NPT)", "nuclear_nonproliferation",
     "1968-07-01", "in_force",
     "Cornerstone treaty limiting the spread of nuclear weapons; near-universal membership.",
     [("USA", 1), ("RUS", 1), ("GBR", 1), ("FRA", 1), ("CHN", 1), ("IRN", 1), ("DEU", 1),
      ("JPN", 1), ("KOR", 1), ("UKR", 1)]),
    ("Paris Agreement", "environmental", "2015-12-12", "in_force",
     "Global framework limiting warming to well below 2°C.",
     [("USA", 1), ("CHN", 1), ("IND", 1), ("DEU", 1), ("FRA", 1), ("GBR", 1), ("BRA", 1),
      ("JPN", 1), ("RUS", 1)]),
    ("USMCA", "trade", "2018-11-30", "in_force",
     "United States–Mexico–Canada free trade agreement (NAFTA successor).",
     [("USA", 1), ("MEX", 1), ("CAN", 1)]),
    ("Abraham Accords", "peace_accord", "2020-09-15", "in_force",
     "Normalization agreements between Israel and several Arab states.",
     [("ISR", 1), ("ARE", 1)]),
    ("New START", "nuclear_nonproliferation", "2010-04-08", "expired",
     "US–Russia strategic arms reduction treaty; lapsed February 2026 without replacement.",
     [("USA", 1), ("RUS", 1)]),
]

# (imposing_type, imposing_ref, target_iso3, target_nsa, reason, imposed, status)
SANCTIONS = [
    ("country", "USA", "RUS", None,
     "Sweeping sanctions over the invasion of Ukraine (financial, energy, export controls).",
     "2022-02-24", "active"),
    ("alliance", "European Union", "RUS", None,
     "Successive EU sanction packages over the war in Ukraine.", "2022-02-25", "active"),
    ("country", "USA", "IRN", None,
     "Sanctions over nuclear program and regional activities.", "2018-11-05", "active"),
    ("country", "USA", "PRK", None,
     "Sanctions over nuclear weapons and ballistic missile programs.", "2016-02-18", "active"),
    ("country", "USA", "VEN", None,
     "Sanctions on government and oil sector.", "2019-01-28", "active"),
    ("international_organization", "United Nations", "PRK", None,
     "UN Security Council resolutions over nuclear tests.", "2006-10-14", "active"),
    ("country", "USA", None, "Hezbollah",
     "Designated terrorist organization; financial network sanctions.", "1997-10-08", "active"),
]

# (name, role, country_iso3, org_name, nsa_name, bio)
NOTABLE_PERSONS = [
    ("Marco Rubio", "Secretary of State", "USA", None, None,
     "Chief US diplomat under the second Trump administration."),
    ("Wang Yi", "Foreign Minister", "CHN", None, None,
     "China's top diplomat, director of the CCP Central Foreign Affairs Commission Office."),
    ("Sergei Lavrov", "Foreign Minister", "RUS", None, None,
     "Russia's foreign minister since 2004."),
    ("Jerome Powell", "Federal Reserve Chair", "USA", None, None,
     "Chair of the US central bank; term expires May 2026."),
    ("Christine Lagarde", "ECB President", None, None, None,
     "President of the European Central Bank."),
    ("António Guterres", "UN Secretary-General", None, "United Nations", None,
     "Ninth Secretary-General of the United Nations."),
    ("Kristalina Georgieva", "IMF Managing Director", None, "International Monetary Fund", None,
     "Managing Director of the International Monetary Fund."),
    ("Volodymyr Zelenskyy", "President", "UKR", None, None,
     "President of Ukraine; wartime leader since the 2022 invasion."),
    ("Mohammed bin Salman", "Crown Prince / PM", "SAU", None, None,
     "De facto ruler of Saudi Arabia."),
    ("Abdel Fattah al-Burhan", "SAF Commander", "SDN", None, None,
     "Head of Sudan's Sovereignty Council and armed forces commander."),
]

# (iso3, type, date, status, result)
ELECTIONS = [
    ("USA", "parliamentary", "2026-11-03", "upcoming", None),
    ("BRA", "presidential", "2026-10-04", "upcoming", None),
    ("HUN", "parliamentary", "2026-04-12", "upcoming", None),
    ("FRA", "presidential", "2027-04-11", "upcoming", None),
    ("KOR", "presidential", "2025-06-03", "completed",
     "Lee Jae-myung (Democratic Party) won the snap election following impeachment."),
    ("DEU", "parliamentary", "2025-02-23", "completed",
     "CDU/CSU led; Friedrich Merz formed a coalition government."),
    ("CAN", "parliamentary", "2025-04-28", "completed",
     "Liberal Party under Mark Carney retained government."),
    ("ARG", "parliamentary", "2025-10-26", "completed",
     "Midterm legislative elections strengthened La Libertad Avanza."),
]


# ===== v4 §5 — entity data completeness =====
# Generated from Natural Earth admin-0 attributes + populated places
# (public domain) so the country layer covers the full UN membership plus
# observers and commonly-recognized de facto states — a completeness
# guarantee, not a bigger hand-curated list (v4 §5.1). government_type is
# left NULL where not curated; the Wikidata sync fills leadership.

COUNTRIES_V4_EXTRA = [
    ('AGO', 'Angola', 'Luanda', 'Middle Africa', None, -8.84, 13.23),
    ('ALB', 'Albania', 'Tirana', 'Southern Europe', None, 41.33, 19.82),
    ('AND', 'Andorra', 'Andorra', 'Southern Europe', None, 42.5, 1.52),
    ('ATG', 'Antigua and Barbuda', "Saint John's", 'Caribbean', None, 17.12, -61.85),
    ('AUT', 'Austria', 'Vienna', 'Western Europe', None, 48.2, 16.36),
    ('BDI', 'Burundi', 'Bujumbura', 'Eastern Africa', None, -3.38, 29.36),
    ('BEL', 'Belgium', 'Brussels', 'Western Europe', None, 50.84, 4.33),
    ('BEN', 'Benin', 'Cotonou', 'Western Africa', None, 6.4, 2.52),
    ('BGR', 'Bulgaria', 'Sofia', 'Eastern Europe', None, 42.69, 23.31),
    ('BHR', 'Bahrain', 'Manama', 'Western Asia', None, 26.24, 50.58),
    ('BHS', 'Bahamas', 'Nassau', 'Caribbean', None, 25.08, -77.35),
    ('BIH', 'Bosnia and Herzegovina', 'Sarajevo', 'Southern Europe', None, 43.85, 18.38),
    ('BLZ', 'Belize', 'Belmopan', 'Central America', None, 17.25, -88.77),
    ('BOL', 'Bolivia', 'La Paz', 'South America', None, -16.5, -68.15),
    ('BRB', 'Barbados', 'Bridgetown', 'Caribbean', None, 13.1, -59.62),
    ('BRN', 'Brunei Darussalam', 'Bandar Seri Begawan', 'South-Eastern Asia', None, 4.88, 114.93),
    ('BTN', 'Bhutan', 'Thimphu', 'Southern Asia', None, 27.47, 89.64),
    ('BWA', 'Botswana', 'Gaborone', 'Southern Africa', None, -24.65, 25.91),
    ('CAF', 'Central African Republic', 'Bangui', 'Middle Africa', None, 4.37, 18.56),
    ('CIV', "Côte d'Ivoire", 'Abidjan', 'Western Africa', None, 5.32, -4.04),
    ('CMR', 'Cameroon', 'Yaoundé', 'Middle Africa', None, 3.87, 11.51),
    ('COG', 'Republic of the Congo', 'Brazzaville', 'Middle Africa', None, -4.26, 15.28),
    ('COM', 'Comoros', 'Moroni', 'Eastern Africa', None, -11.7, 43.24),
    ('CPV', 'Republic of Cabo Verde', 'Praia', 'Western Africa', None, 14.92, -23.52),
    ('CRI', 'Costa Rica', 'San José', 'Central America', None, 9.94, -84.09),
    ('CYN', 'Northern Cyprus', 'North Nicosia', 'Western Asia', None, 35.19, 33.36),
    ('CYP', 'Cyprus', 'Nicosia', 'Western Asia', None, 35.17, 33.37),
    ('DJI', 'Djibouti', 'Djibouti', 'Eastern Africa', None, 11.6, 43.15),
    ('DMA', 'Dominica', 'Roseau', 'Caribbean', None, 15.3, -61.39),
    ('DNK', 'Denmark', 'Copenhagen', 'Northern Europe', None, 55.68, 12.56),
    ('DOM', 'Dominican Republic', 'Santo Domingo', 'Caribbean', None, 18.47, -69.9),
    ('ECU', 'Ecuador', 'Quito', 'South America', None, -0.21, -78.5),
    ('ERI', 'Eritrea', 'Asmara', 'Eastern Africa', None, 15.33, 38.93),
    ('EST', 'Estonia', 'Tallinn', 'Northern Europe', None, 59.43, 24.73),
    ('FJI', 'Fiji', 'Suva', 'Melanesia', None, -18.13, 178.44),
    ('FSM', 'Federated States of Micronesia', 'Palikir', 'Micronesia', None, 6.92, 158.15),
    ('GAB', 'Gabon', 'Libreville', 'Middle Africa', None, 0.39, 9.46),
    ('GHA', 'Ghana', 'Accra', 'Western Africa', None, 5.55, -0.22),
    ('GIN', 'Guinea', 'Conakry', 'Western Africa', None, 9.53, -13.68),
    ('GMB', 'The Gambia', 'Banjul', 'Western Africa', None, 13.45, -16.59),
    ('GNB', 'Guinea-Bissau', 'Bissau', 'Western Africa', None, 11.87, -15.6),
    ('GNQ', 'Equatorial Guinea', 'Malabo', 'Middle Africa', None, 3.75, 8.78),
    ('GRD', 'Grenada', "Saint George's", 'Caribbean', None, 12.05, -61.74),
    ('GTM', 'Guatemala', 'Guatemala City', 'Central America', None, 14.62, -90.53),
    ('GUY', 'Guyana', 'Georgetown', 'South America', None, 6.8, -58.17),
    ('HND', 'Honduras', 'Tegucigalpa', 'Central America', None, 14.1, -87.22),
    ('HRV', 'Croatia', 'Zagreb', 'Southern Europe', None, 45.8, 16.0),
    ('HTI', 'Haiti', 'Port-au-Prince', 'Caribbean', None, 18.54, -72.34),
    ('IRL', 'Ireland', 'Dublin', 'Northern Europe', None, 53.34, -6.25),
    ('ISL', 'Iceland', 'Reykjavík', 'Northern Europe', None, 64.15, -21.95),
    ('JAM', 'Jamaica', 'Kingston', 'Caribbean', None, 17.98, -76.77),
    ('KGZ', 'Kyrgyzstan', 'Bishkek', 'Central Asia', None, 42.88, 74.58),
    ('KHM', 'Cambodia', 'Phnom Penh', 'South-Eastern Asia', None, 11.55, 104.91),
    ('KIR', 'Kiribati', 'Tarawa', 'Micronesia', None, 1.34, 173.02),
    ('KNA', 'Saint Kitts and Nevis', 'Basseterre', 'Caribbean', None, 17.3, -62.72),
    ('KWT', 'Kuwait', 'Kuwait City', 'Western Asia', None, 29.37, 47.98),
    ('LAO', 'Lao PDR', 'Vientiane', 'South-Eastern Asia', None, 17.97, 102.6),
    ('LBR', 'Liberia', 'Monrovia', 'Western Africa', None, 6.31, -10.8),
    ('LCA', 'Saint Lucia', 'Castries', 'Caribbean', None, 14.0, -61.0),
    ('LIE', 'Liechtenstein', 'Vaduz', 'Western Europe', None, 47.13, 9.52),
    ('LKA', 'Sri Lanka', 'Colombo', 'Southern Asia', None, 6.93, 79.86),
    ('LSO', 'Lesotho', 'Maseru', 'Southern Africa', None, -29.32, 27.48),
    ('LTU', 'Lithuania', 'Vilnius', 'Northern Europe', None, 54.68, 25.32),
    ('LUX', 'Luxembourg', 'Luxembourg', 'Western Europe', None, 49.61, 6.13),
    ('LVA', 'Latvia', 'Riga', 'Northern Europe', None, 56.95, 24.1),
    ('MCO', 'Monaco', 'Monaco', 'Western Europe', None, 43.74, 7.41),
    ('MDA', 'Moldova', 'Chișinău', 'Eastern Europe', None, 47.01, 28.86),
    ('MDG', 'Madagascar', 'Antananarivo', 'Eastern Africa', None, -18.91, 47.51),
    ('MDV', 'Maldives', 'Malé', 'Southern Asia', None, 4.17, 73.5),
    ('MHL', 'Marshall Islands', 'Majuro', 'Micronesia', None, 7.1, 171.38),
    ('MKD', 'North Macedonia', 'Skopje', 'Southern Europe', None, 42.0, 21.43),
    ('MLT', 'Malta', 'Valletta', 'Southern Europe', None, 35.9, 14.51),
    ('MNE', 'Montenegro', 'Podgorica', 'Southern Europe', None, 42.47, 19.27),
    ('MNG', 'Mongolia', 'Ulaanbaatar', 'Eastern Asia', None, 47.92, 106.91),
    ('MOZ', 'Mozambique', 'Maputo', 'Eastern Africa', None, -25.95, 32.59),
    ('MRT', 'Mauritania', 'Nouakchott', 'Western Africa', None, 18.09, -15.98),
    ('MUS', 'Mauritius', 'Port Louis', 'Eastern Africa', None, -20.17, 57.5),
    ('MWI', 'Malawi', 'Lilongwe', 'Eastern Africa', None, -13.98, 33.78),
    ('NAM', 'Namibia', 'Windhoek', 'Southern Africa', None, -22.57, 17.08),
    ('NIC', 'Nicaragua', 'Managua', 'Central America', None, 12.15, -86.27),
    ('NPL', 'Nepal', 'Kathmandu', 'Southern Asia', None, 27.72, 85.31),
    ('NRU', 'Nauru', None, 'Micronesia', None, None, None),
    ('OMN', 'Oman', 'Muscat', 'Western Asia', None, 23.61, 58.59),
    ('PAN', 'Panama', 'Panama City', 'Central America', None, 8.97, -79.53),
    ('PER', 'Peru', 'Lima', 'South America', None, -12.05, -77.05),
    ('PLW', 'Palau', 'Melekeok', 'Micronesia', None, 7.49, 134.63),
    ('PNG', 'Papua New Guinea', 'Port Moresby', 'Melanesia', None, -9.46, 147.19),
    ('PRY', 'Paraguay', 'Asunción', 'South America', None, -25.29, -57.64),
    ('PSE', 'Palestine', 'Ramallah', 'Western Asia', None, 31.9, 35.2),
    ('RWA', 'Rwanda', 'Kigali', 'Eastern Africa', None, -1.95, 30.06),
    ('SEN', 'Senegal', 'Dakar', 'Western Africa', None, 14.72, -17.48),
    ('SLB', 'Solomon Islands', 'Honiara', 'Melanesia', None, -9.44, 159.95),
    ('SLE', 'Sierra Leone', 'Freetown', 'Western Africa', None, 8.47, -13.24),
    ('SLV', 'El Salvador', 'San Salvador', 'Central America', None, 13.71, -89.2),
    ('SMR', 'San Marino', 'San Marino', 'Southern Europe', None, 43.94, 12.44),
    ('SOL', 'Somaliland', 'Hargeisa', 'Eastern Africa', None, 9.56, 44.07),
    ('STP', 'São Tomé and Principe', 'São Tomé', 'Middle Africa', None, 0.33, 6.73),
    ('SUR', 'Suriname', 'Paramaribo', 'South America', None, 5.84, -55.17),
    ('SVK', 'Slovakia', 'Bratislava', 'Eastern Europe', None, 48.15, 17.12),
    ('SVN', 'Slovenia', 'Ljubljana', 'Southern Europe', None, 46.06, 14.51),
    ('SWZ', 'Kingdom of eSwatini', 'Mbabane', 'Southern Africa', None, -26.32, 31.13),
    ('SYC', 'Seychelles', 'Victoria', 'Eastern Africa', None, -4.62, 55.45),
    ('TCD', 'Chad', "N'Djamena", 'Middle Africa', None, 12.12, 15.05),
    ('TGO', 'Togo', 'Lomé', 'Western Africa', None, 6.13, 1.22),
    ('TJK', 'Tajikistan', 'Dushanbe', 'Central Asia', None, 38.56, 68.77),
    ('TKM', 'Turkmenistan', 'Ashgabat', 'Central Asia', None, 37.95, 58.38),
    ('TLS', 'Timor-Leste', 'Dili', 'South-Eastern Asia', None, -8.56, 125.58),
    ('TON', 'Tonga', "Nuku'alofa", 'Polynesia', None, -21.14, -175.22),
    ('TTO', 'Trinidad and Tobago', 'Port-of-Spain', 'Caribbean', None, 10.65, -61.52),
    ('TUN', 'Tunisia', 'Tunis', 'Northern Africa', None, 36.8, 10.18),
    ('TUV', 'Tuvalu', 'Funafuti', 'Polynesia', None, -8.52, 179.22),
    ('TZA', 'Tanzania', 'Dar es Salaam', 'Eastern Africa', None, -6.8, 39.27),
    ('UGA', 'Uganda', 'Kampala', 'Eastern Africa', None, 0.32, 32.58),
    ('URY', 'Uruguay', 'Montevideo', 'South America', None, -34.86, -56.17),
    ('UZB', 'Uzbekistan', 'Tashkent', 'Central Asia', None, 41.31, 69.29),
    ('VAT', 'Vatican City', 'Vatican City', 'Southern Europe', None, 41.9, 12.45),
    ('VCT', 'Saint Vincent and the Grenadines', 'Kingstown', 'Caribbean', None, 13.15, -61.21),
    ('VUT', 'Vanuatu', 'Port Vila', 'Melanesia', None, -17.73, 168.32),
    ('WSM', 'Samoa', 'Apia', 'Polynesia', None, -13.84, -171.74),
    ('XKX', 'Kosovo', 'Pristina', 'Southern Europe', None, 42.67, 21.17),
    ('ZMB', 'Zambia', 'Lusaka', 'Eastern Africa', None, -15.41, 28.28),
    ('ZWE', 'Zimbabwe', 'Harare', 'Eastern Africa', None, -17.82, 31.04),
]

COUNTRY_STATUS = {
    'CYN': 'de_facto',
    'PSE': 'observer_state',
    'SOL': 'de_facto',
    'TWN': 'de_facto',
    'VAT': 'observer_state',
    'XKX': 'de_facto',
    # v6 §21/§15 — Taliban-governed Afghanistan: UN seat contested, governing
    # authority unrecognized by most states, so the honest status is de_facto
    'AFG': 'de_facto',
}

# v6 §21 — non-state actors that became a country's actual governing
# authority get reclassified out of non_state_actors (their zones and rows
# removed; leadership carried on the country instead). Generalized as data,
# not a one-off Taliban patch: any future case is one line here, and the
# completeness check flags NSAs whose descriptions read like governments.
NSA_GOVERNING_RECLASSIFICATIONS = [
    ("Taliban", "AFG"),
]

COUNTRY_ISO2 = {
    'AFG': 'AF', 'AGO': 'AO', 'ALB': 'AL', 'AND': 'AD', 'ARE': 'AE', 'ARG': 'AR',
    'ARM': 'AM', 'ATG': 'AG', 'AUS': 'AU', 'AUT': 'AT', 'AZE': 'AZ', 'BDI': 'BI',
    'BEL': 'BE', 'BEN': 'BJ', 'BFA': 'BF', 'BGD': 'BD', 'BGR': 'BG', 'BHR': 'BH',
    'BHS': 'BS', 'BIH': 'BA', 'BLR': 'BY', 'BLZ': 'BZ', 'BOL': 'BO', 'BRA': 'BR',
    'BRB': 'BB', 'BRN': 'BN', 'BTN': 'BT', 'BWA': 'BW', 'CAF': 'CF', 'CAN': 'CA',
    'CHE': 'CH', 'CHL': 'CL', 'CHN': 'CN', 'CIV': 'CI', 'CMR': 'CM', 'COD': 'CD',
    'COG': 'CG', 'COL': 'CO', 'COM': 'KM', 'CPV': 'CV', 'CRI': 'CR', 'CUB': 'CU',
    'CYN': None, 'CYP': 'CY', 'CZE': 'CZ', 'DEU': 'DE', 'DJI': 'DJ', 'DMA': 'DM',
    'DNK': 'DK', 'DOM': 'DO', 'DZA': 'DZ', 'ECU': 'EC', 'EGY': 'EG', 'ERI': 'ER',
    'ESP': 'ES', 'EST': 'EE', 'ETH': 'ET', 'FIN': 'FI', 'FJI': 'FJ', 'FRA': 'FR',
    'FSM': 'FM', 'GAB': 'GA', 'GBR': 'GB', 'GEO': 'GE', 'GHA': 'GH', 'GIN': 'GN',
    'GMB': 'GM', 'GNB': 'GW', 'GNQ': 'GQ', 'GRC': 'GR', 'GRD': 'GD', 'GTM': 'GT',
    'GUY': 'GY', 'HND': 'HN', 'HRV': 'HR', 'HTI': 'HT', 'HUN': 'HU', 'IDN': 'ID',
    'IND': 'IN', 'IRL': 'IE', 'IRN': 'IR', 'IRQ': 'IQ', 'ISL': 'IS', 'ISR': 'IL',
    'ITA': 'IT', 'JAM': 'JM', 'JOR': 'JO', 'JPN': 'JP', 'KAZ': 'KZ', 'KEN': 'KE',
    'KGZ': 'KG', 'KHM': 'KH', 'KIR': 'KI', 'KNA': 'KN', 'KOR': 'KR', 'KWT': 'KW',
    'LAO': 'LA', 'LBN': 'LB', 'LBR': 'LR', 'LBY': 'LY', 'LCA': 'LC', 'LIE': 'LI',
    'LKA': 'LK', 'LSO': 'LS', 'LTU': 'LT', 'LUX': 'LU', 'LVA': 'LV', 'MAR': 'MA',
    'MCO': 'MC', 'MDA': 'MD', 'MDG': 'MG', 'MDV': 'MV', 'MEX': 'MX', 'MHL': 'MH',
    'MKD': 'MK', 'MLI': 'ML', 'MLT': 'MT', 'MMR': 'MM', 'MNE': 'ME', 'MNG': 'MN',
    'MOZ': 'MZ', 'MRT': 'MR', 'MUS': 'MU', 'MWI': 'MW', 'MYS': 'MY', 'NAM': 'NA',
    'NER': 'NE', 'NGA': 'NG', 'NIC': 'NI', 'NLD': 'NL', 'NOR': 'NO', 'NPL': 'NP',
    'NRU': 'NR', 'NZL': 'NZ', 'OMN': 'OM', 'PAK': 'PK', 'PAN': 'PA', 'PER': 'PE',
    'PHL': 'PH', 'PLW': 'PW', 'PNG': 'PG', 'POL': 'PL', 'PRK': 'KP', 'PRT': 'PT',
    'PRY': 'PY', 'PSE': 'PS', 'QAT': 'QA', 'ROU': 'RO', 'RUS': 'RU', 'RWA': 'RW',
    'SAU': 'SA', 'SDN': 'SD', 'SEN': 'SN', 'SGP': 'SG', 'SLB': 'SB', 'SLE': 'SL',
    'SLV': 'SV', 'SMR': 'SM', 'SOL': None, 'SOM': 'SO', 'SRB': 'RS', 'SSD': 'SS',
    'STP': 'ST', 'SUR': 'SR', 'SVK': 'SK', 'SVN': 'SI', 'SWE': 'SE', 'SWZ': 'SZ',
    'SYC': 'SC', 'SYR': 'SY', 'TCD': 'TD', 'TGO': 'TG', 'THA': 'TH', 'TJK': 'TJ',
    'TKM': 'TM', 'TLS': 'TL', 'TON': 'TO', 'TTO': 'TT', 'TUN': 'TN', 'TUR': 'TR',
    'TUV': 'TV', 'TWN': 'TW', 'TZA': 'TZ', 'UGA': 'UG', 'UKR': 'UA', 'URY': 'UY',
    'USA': 'US', 'UZB': 'UZ', 'VAT': 'VA', 'VCT': 'VC', 'VEN': 'VE', 'VNM': 'VN',
    'VUT': 'VU', 'WSM': 'WS', 'XKX': 'XK', 'YEM': 'YE', 'ZAF': 'ZA', 'ZMB': 'ZM',
    'ZWE': 'ZW',
}

COUNTRY_POPULATION = {
    'AFG': 38041754, 'AGO': 31825295, 'ALB': 2854191, 'AND': 77142, 'ARE': 9770529, 'ARG': 44938712,
    'ARM': 2957731, 'ATG': 97118, 'AUS': 25364307, 'AUT': 8877067, 'AZE': 10023318, 'BDI': 11530580,
    'BEL': 11484055, 'BEN': 11801151, 'BFA': 20321378, 'BGD': 163046161, 'BGR': 6975761, 'BHR': 1641172,
    'BHS': 389482, 'BIH': 3301000, 'BLR': 9466856, 'BLZ': 390353, 'BOL': 11513100, 'BRA': 211049527,
    'BRB': 287025, 'BRN': 433285, 'BTN': 763092, 'BWA': 2303697, 'CAF': 4745185, 'CAN': 37589262,
    'CHE': 8574832, 'CHL': 18952038, 'CHN': 1397715000, 'CIV': 25716544, 'CMR': 25876380, 'COD': 86790567,
    'COG': 5380508, 'COL': 50339443, 'COM': 850886, 'CPV': 549935, 'CRI': 5047561, 'CUB': 11333483,
    'CYN': 326000, 'CYP': 1198575, 'CZE': 10669709, 'DEU': 83132799, 'DJI': 973560, 'DMA': 71808,
    'DNK': 5818553, 'DOM': 10738958, 'DZA': 43053054, 'ECU': 17373662, 'EGY': 100388073, 'ERI': 6081196,
    'ESP': 47076781, 'EST': 1326590, 'ETH': 112078730, 'FIN': 5520314, 'FJI': 889953, 'FRA': 67059887,
    'FSM': 113815, 'GAB': 2172579, 'GBR': 66834405, 'GEO': 3720382, 'GHA': 30417856, 'GIN': 12771246,
    'GMB': 2347706, 'GNB': 1920922, 'GNQ': 1355986, 'GRC': 10716322, 'GRD': 112003, 'GTM': 16604026,
    'GUY': 782766, 'HND': 9746117, 'HRV': 4067500, 'HTI': 11263077, 'HUN': 9769949, 'IDN': 270625568,
    'IND': 1366417754, 'IRL': 4941444, 'IRN': 82913906, 'IRQ': 39309783, 'ISL': 361313, 'ISR': 9053300,
    'ITA': 60297396, 'JAM': 2948279, 'JOR': 10101694, 'JPN': 126264931, 'KAZ': 18513930, 'KEN': 52573973,
    'KGZ': 6456900, 'KHM': 16486542, 'KIR': 117606, 'KNA': 52834, 'KOR': 51709098, 'KWT': 4207083,
    'LAO': 7169455, 'LBN': 6855713, 'LBR': 4937374, 'LBY': 6777452, 'LCA': 182790, 'LIE': 38019,
    'LKA': 21803000, 'LSO': 2125268, 'LTU': 2786844, 'LUX': 619896, 'LVA': 1912789, 'MAR': 36471769,
    'MCO': 38964, 'MDA': 2657637, 'MDG': 26969307, 'MDV': 530953, 'MEX': 127575529, 'MHL': 58791,
    'MKD': 2083459, 'MLI': 19658031, 'MLT': 502653, 'MMR': 54045420, 'MNE': 622137, 'MNG': 3225167,
    'MOZ': 30366036, 'MRT': 4525696, 'MUS': 1265711, 'MWI': 18628747, 'MYS': 31949777, 'NAM': 2494530,
    'NER': 23310715, 'NGA': 200963599, 'NIC': 6545502, 'NLD': 17332850, 'NOR': 5347896, 'NPL': 28608710,
    'NRU': 12581, 'NZL': 4917000, 'OMN': 4974986, 'PAK': 216565318, 'PAN': 4246439, 'PER': 32510453,
    'PHL': 108116615, 'PLW': 18008, 'PNG': 8776109, 'POL': 37970874, 'PRK': 25666161, 'PRT': 10269417,
    'PRY': 7044636, 'PSE': 4685306, 'QAT': 2832067, 'ROU': 19356544, 'RUS': 144373535, 'RWA': 12626950,
    'SAU': 34268528, 'SDN': 42813238, 'SEN': 16296364, 'SGP': 5703569, 'SLB': 669823, 'SLE': 7813215,
    'SLV': 6453553, 'SMR': 33860, 'SOL': 5096159, 'SOM': 10192317, 'SRB': 6944975, 'SSD': 11062113,
    'STP': 215056, 'SUR': 581363, 'SVK': 5454073, 'SVN': 2087946, 'SWE': 10285453, 'SWZ': 1148130,
    'SYC': 97625, 'SYR': 17070135, 'TCD': 15946876, 'TGO': 8082366, 'THA': 69625582, 'TJK': 9321018,
    'TKM': 5942089, 'TLS': 1293119, 'TON': 104494, 'TTO': 1394973, 'TUN': 11694719, 'TUR': 83429615,
    'TUV': 11646, 'TWN': 23568378, 'TZA': 58005463, 'UGA': 44269594, 'UKR': 44385155, 'URY': 3461734,
    'USA': 328239523, 'UZB': 33580650, 'VAT': 825, 'VCT': 110589, 'VEN': 28515829, 'VNM': 96462106,
    'VUT': 299882, 'WSM': 197097, 'XKX': 1794248, 'YEM': 29161922, 'ZAF': 58558270, 'ZMB': 17861030,
    'ZWE': 14645468,
}


# v4 §5.3 — border disputes seed. claimant_b None = non-state claimant,
# described in summary. boundary_ref names match the Natural Earth
# disputed-lines layer rendered by the frontend toggle where applicable.
BORDER_DISPUTES = [
    ("IND", "PAK", "Kashmir (Line of Control)", "active",
     "Divided between India and Pakistan since 1947; recurring cross-border escalation."),
    ("IND", "CHN", "Aksai Chin / Line of Actual Control", "active",
     "High-altitude boundary dispute; deadly clashes as recently as 2020-2022."),
    ("CHN", "IND", "Arunachal Pradesh (South Tibet claim)", "frozen",
     "China claims the Indian state of Arunachal Pradesh as South Tibet."),
    ("RUS", "UKR", "Crimea and occupied Ukrainian oblasts", "active",
     "Annexed/occupied by Russia since 2014/2022; internationally recognized as Ukraine."),
    # v6 §7 — all four Russian-occupied Ukrainian regions as ONE dispute entry
    # (de-facto annexation 2022, still internationally disputed)
    ("UKR", "RUS", "Donetsk, Luhansk, Zaporizhzhia and Kherson oblasts (Russian-occupied)",
     "active",
     "The four Ukrainian oblasts Russia declared annexed in September 2022 —"
     " Donetsk, Luhansk, Zaporizhzhia and Kherson — partially occupied, plus"
     " small Russian-held border strips of Kharkiv oblast; all internationally"
     " recognized as Ukrainian territory. Crimea (annexed 2014) tracked separately."),
    ("RUS", "JPN", "Kuril Islands / Northern Territories", "frozen",
     "Soviet-occupied since 1945; blocks a formal WWII peace treaty."),
    ("JPN", "KOR", "Liancourt Rocks (Dokdo/Takeshima)", "frozen",
     "Administered by South Korea, claimed by Japan."),
    ("CHN", "TWN", "Taiwan Strait", "active",
     "The PRC claims Taiwan; Taiwan functions as a de facto state (see countries.status)."),
    ("CHN", "PHL", "Spratly Islands / South China Sea", "active",
     "Overlapping claims by six parties; militarized artificial islands and standoffs."),
    ("ISR", "SYR", "Golan Heights", "frozen",
     "Israeli-occupied since 1967, annexation not widely recognized."),
    ("ISR", "PSE", "West Bank, Gaza and East Jerusalem", "active",
     "Core territorial dimension of the Israel-Palestine conflict."),
    ("MAR", None, "Western Sahara", "active",
     "Morocco controls most of the territory; the Polisario Front (SADR) claims independence."),
    ("ARM", "AZE", "Nagorno-Karabakh", "resolved",   # v6.6 — Armenia recognizes AZ control
     "Azerbaijan retook the territory in 2023; peace-treaty talks continue."),
    ("GBR", "ARG", "Falkland Islands / Malvinas", "frozen",
     "UK-administered; Argentina maintains its claim (1982 war)."),
    ("GBR", "ESP", "Gibraltar", "frozen",
     "British Overseas Territory claimed by Spain."),
    ("VEN", "GUY", "Essequibo", "active",
     "Venezuela claims two-thirds of Guyana; 2023 referendum escalated tensions."),
    ("SDN", "SSD", "Abyei", "active",
     "Oil-rich area contested since South Sudan's independence."),
    ("EGY", "SDN", "Hala'ib Triangle", "frozen",
     "Administered by Egypt, claimed by Sudan."),
    ("CYP", "CYN", "Northern Cyprus", "frozen",
     "Turkish-occupied north recognized only by Turkey (see countries.status de_facto)."),
    ("SOM", "SOL", "Somaliland", "frozen",
     "Self-governing since 1991; unrecognized but functioning de facto state."),
    ("MDA", None, "Transnistria", "frozen",
     "Russian-backed breakaway strip on the Dniester; unrecognized."),
    ("GEO", "RUS", "Abkhazia and South Ossetia", "frozen",
     "Russian-recognized breakaways after the 2008 war; internationally Georgia."),
    ("SRB", "XKX", "Kosovo", "frozen",
     "Kosovo declared independence 2008; recognized by ~100 states, not by Serbia."),
    ("THA", "KHM", "Preah Vihear temple area", "frozen",
     "ICJ ruled for Cambodia; border demarcation friction persists."),
    ("GTM", "BLZ", "Belize territorial claim", "frozen",
     "Guatemala's claim referred to the ICJ by both parties."),
]

# v4 §6.2 — political parties as first-class wiki entities.
# (name, iso3, ideology_tags, founded)
# v6 §5 — leader & party profile depth: electoral history, coalitions,
# founding history, portraits. Keyed by seed name; JSON-ready values.
# Sourced from published election results; refreshed by the §30 pipeline.
PARTY_ENRICHMENT = {
    "Republican Party": {
        "electoral_history": [{"election": "2024 US presidential", "result": "won (Trump 312 EV)"},
                              {"election": "2024 House", "result": "majority (220 seats)"},
                              {"election": "2020 US presidential", "result": "lost (Trump 232 EV)"}],
        "coalition_partners": [],
        "founding_history": "Founded 1854 by anti-slavery activists opposing the Kansas-Nebraska Act; first won the presidency with Lincoln in 1860.",
    },
    "Democratic Party (US)": {
        "electoral_history": [{"election": "2024 US presidential", "result": "lost (Harris 226 EV)"},
                              {"election": "2020 US presidential", "result": "won (Biden 306 EV)"}],
        "coalition_partners": [],
        "founding_history": "Traces to Jefferson's Democratic-Republicans; organized under Jackson in 1828, making it one of the world's oldest active parties.",
    },
    "Communist Party of China": {
        "electoral_history": [{"election": "one-party system", "result": "governing since 1949"}],
        "coalition_partners": ["Eight minor 'united front' parties (non-competitive)"],
        "founding_history": "Founded in Shanghai in 1921; took power in 1949 after the Chinese Civil War.",
    },
    "United Russia": {
        "electoral_history": [{"election": "2021 State Duma", "result": "won (324/450 seats)"},
                              {"election": "2016 State Duma", "result": "won (343/450 seats)"}],
        "coalition_partners": ["Systemic opposition votes with government (LDPR, CPRF on key items)"],
        "founding_history": "Formed 2001 from the merger of Unity and Fatherland-All Russia as Putin's dominant vehicle.",
    },
    "Labour Party (UK)": {
        "electoral_history": [{"election": "2024 UK general", "result": "won (411/650 seats)"},
                              {"election": "2019 UK general", "result": "lost (202 seats)"}],
        "coalition_partners": [],
        "founding_history": "Founded 1900 from the trade-union movement; first majority government 1945 under Attlee.",
    },
    "Conservative Party (UK)": {
        "electoral_history": [{"election": "2024 UK general", "result": "lost (121/650 seats)"},
                              {"election": "2019 UK general", "result": "won (365 seats)"}],
        "coalition_partners": [],
        "founding_history": "Descended from the Tories; organized as the modern Conservative Party under Peel after 1834.",
    },
    "Bharatiya Janata Party": {
        "electoral_history": [{"election": "2024 Lok Sabha", "result": "won (240 seats, NDA coalition)"},
                              {"election": "2019 Lok Sabha", "result": "won (303 seats)"}],
        "coalition_partners": ["National Democratic Alliance (TDP, JD(U) and others)"],
        "founding_history": "Founded 1980 from the Jana Sangh tradition; dominant national party since 2014 under Modi.",
    },
    "Renaissance": {
        "electoral_history": [{"election": "2024 French legislative", "result": "second (Ensemble 168 seats)"},
                              {"election": "2022 presidential", "result": "won (Macron 58.5%)"}],
        "coalition_partners": ["Ensemble coalition (MoDem, Horizons)"],
        "founding_history": "Founded 2016 as En Marche! by Emmanuel Macron; renamed Renaissance in 2022.",
    },
    "CDU": {
        "electoral_history": [{"election": "2025 Bundestag", "result": "won (CDU/CSU 208 seats)"},
                              {"election": "2021 Bundestag", "result": "lost (197 seats)"}],
        "coalition_partners": ["CSU (permanent union)", "SPD (grand coalition 2025)"],
        "founding_history": "Founded 1945 as a cross-confessional Christian-democratic party; led West Germany's postwar reconstruction under Adenauer.",
    },
    "Brothers of Italy": {
        "electoral_history": [{"election": "2022 Italian general", "result": "won (26%, Meloni PM)"}],
        "coalition_partners": ["Lega", "Forza Italia"],
        "founding_history": "Founded 2012 from the post-fascist MSI/AN tradition; first party of government from 2022.",
    },
}

PERSON_ENRICHMENT = {
    "Volodymyr Zelenskyy": {
        "electoral_history": [{"election": "2019 Ukrainian presidential", "result": "won (73.2% runoff)"}],
        "portrait": "Volodymyr Zelensky Official portrait.jpg",
    },
    "Sergei Lavrov": {
        "electoral_history": [{"election": "appointed office", "result": "Foreign Minister since 2004"}],
        "portrait": None,
    },
    "Marco Rubio": {
        "electoral_history": [{"election": "2022 US Senate (Florida)", "result": "won (57.7%)"},
                              {"election": "2016 US Senate (Florida)", "result": "won (52.0%)"}],
        "portrait": None,
    },
    "Wang Yi": {
        "electoral_history": [{"election": "appointed office", "result": "Foreign Minister 2013-2023, reappointed 2023"}],
        "portrait": None,
    },
}

POLITICAL_PARTIES = [
    ("Republican Party", "USA", "conservative;right", "1854-03-20"),
    ("Democratic Party (US)", "USA", "liberal;center-left", "1828-01-08"),
    ("Communist Party of China", "CHN", "communist;one-party", "1921-07-23"),
    ("United Russia", "RUS", "statist;dominant-party", "2001-12-01"),
    ("Labour Party (UK)", "GBR", "social-democratic;center-left", "1900-02-27"),
    ("Conservative Party (UK)", "GBR", "conservative;center-right", "1834-12-09"),
    ("Renaissance", "FRA", "liberal;centrist", "2016-04-06"),
    ("National Rally", "FRA", "nationalist;right", "1972-10-05"),
    ("CDU", "DEU", "christian-democratic;center-right", "1945-06-26"),
    ("SPD", "DEU", "social-democratic;center-left", "1863-05-23"),
    ("Brothers of Italy", "ITA", "national-conservative;right", "2012-12-17"),
    ("Bharatiya Janata Party", "IND", "hindu-nationalist;right", "1980-04-06"),
    ("Indian National Congress", "IND", "big-tent;center", "1885-12-28"),
    ("Liberal Democratic Party (Japan)", "JPN", "conservative;center-right", "1955-11-15"),
    ("Workers' Party (Brazil)", "BRA", "democratic-socialist;left", "1980-02-10"),
    ("Likud", "ISR", "national-liberal;right", "1973-09-13"),
    ("Justice and Development Party (AKP)", "TUR", "islamist-conservative;right", "2001-08-14"),
    ("Servant of the People", "UKR", "big-tent;centrist", "2018-03-31"),
    ("Law and Justice (PiS)", "POL", "national-conservative;right", "2001-06-13"),
    ("Civic Platform", "POL", "liberal-conservative;center", "2001-01-24"),
    ("Morena", "MEX", "left-populist", "2011-10-02"),
    ("La Libertad Avanza", "ARG", "libertarian;right", "2021-07-14"),
    ("African National Congress", "ZAF", "social-democratic;big-tent", "1912-01-08"),
    ("Democratic Progressive Party", "TWN", "progressive;center-left", "1986-09-28"),
    ("Kuomintang", "TWN", "conservative;center-right", "1919-10-10"),
    ("Liberal Party of Canada", "CAN", "liberal;center", "1867-07-01"),
    ("People's Action Party", "SGP", "conservative;dominant-party", "1954-11-21"),
    ("Democratic Party of Korea", "KOR", "liberal;center-left", "2015-12-28"),
    ("People Power Party", "KOR", "conservative;right", "2020-02-17"),
    ("Communist Party of Vietnam", "VNM", "communist;one-party", "1930-02-03"),
]

# v4 §5.4 — approximate primary-operating-area centroids so the NSA layer
# is toggleable on the map (honest approximation, labeled as such in UI).
NSA_BASE_COORDS = {
    "Hamas": (31.5, 34.45),
    "Hezbollah": (33.85, 35.9),
    "Houthi Movement (Ansar Allah)": (15.35, 44.2),
    "JNIM (al-Qaeda in the Sahel)": (16.0, -2.0),
    "Islamic State Sahel Province": (15.0, 1.0),
    "Rapid Support Forces": (14.5, 27.0),
    "M23 Movement": (-1.5, 29.2),
    "People's Defence Forces (Myanmar)": (21.0, 95.5),
}

# v5 §11 — rough, deliberately coarse territory/zone polygons per non-state
# actor (descriptive geopolitical context à la ACLED/Liveuamap, NOT precise
# operational boundaries). (nsa_name, confidence, [ [lon,lat]... ] ring).
NSA_ZONES = [
    ("Hamas", "established",
     [[34.2, 31.6], [34.57, 31.6], [34.57, 31.22], [34.2, 31.22], [34.2, 31.6]]),
    ("Hezbollah", "established",
     [[35.1, 34.7], [36.6, 34.6], [36.4, 33.3], [35.2, 33.1], [35.1, 34.7]]),
    ("Houthi Movement (Ansar Allah)", "contested",
     [[42.6, 17.5], [45.5, 16.8], [45.0, 14.0], [43.2, 13.6], [42.6, 15.3], [42.6, 17.5]]),
    ("Rapid Support Forces", "contested",
     [[22.0, 16.0], [28.0, 15.5], [27.5, 11.5], [22.5, 12.0], [22.0, 16.0]]),
    ("M23 Movement", "contested",
     [[28.8, -0.9], [29.7, -1.0], [29.6, -2.1], [28.9, -2.0], [28.8, -0.9]]),
    ("JNIM (al-Qaeda in the Sahel)", "reported",
     [[-8.0, 17.5], [3.0, 16.5], [2.5, 12.5], [-7.5, 13.5], [-8.0, 17.5]]),
    ("Islamic State Sahel Province", "reported",
     [[-1.0, 16.0], [4.0, 15.5], [3.5, 12.5], [-1.5, 13.0], [-1.0, 16.0]]),
    ("People's Defence Forces (Myanmar)", "contested",
     [[94.0, 24.5], [98.0, 23.5], [97.5, 18.0], [94.5, 18.5], [94.0, 24.5]]),
]
