"""v8.16 — curated trade + resources + industry data for the tracking windows.

HONESTY NOTE (the project's standing rule): there is NO free real-time
bilateral-trade feed — UN Comtrade and national customs publish with months
of lag and are not reachable from every deployment. So these windows lead
with a CURATED, clearly-year-labelled statistical layer (WTO/Comtrade/World
Bank vintages as cited per row) and are augmented by the LIVE layers that do
exist: market-price events from the market source, trade/tariff NEWS from
the fact chain, and prediction-market odds. Figures are USD billions unless
stated. Every consumer must render the year + source with the number.
"""

# iso3 → {total_exports, total_imports, year, src, partners: [(iso3, share%)],
#         top_exports: [...], top_imports: [...]}
TRADE = {
    "USA": {"exports": 3053, "imports": 3827, "year": 2023, "src": "BEA/WTO",
            "partners": [("CAN", 17.3), ("MEX", 15.7), ("CHN", 7.3), ("JPN", 4.5), ("GBR", 4.3)],
            "top_exports": ["Refined petroleum", "Crude petroleum", "Natural gas", "Aircraft", "Semiconductors"],
            "top_imports": ["Vehicles", "Crude petroleum", "Electronics", "Pharmaceuticals", "Machinery"]},
    "CHN": {"exports": 3380, "imports": 2557, "year": 2023, "src": "GACC/WTO",
            "partners": [("USA", 14.8), ("HKG", 8.4), ("JPN", 4.6), ("KOR", 4.4), ("VNM", 4.3)],
            "top_exports": ["Electronics", "Machinery", "Vehicles & EVs", "Solar panels", "Textiles"],
            "top_imports": ["Semiconductors", "Crude petroleum", "Iron ore", "Soybeans", "Natural gas"]},
    "DEU": {"exports": 1688, "imports": 1463, "year": 2023, "src": "Destatis",
            "partners": [("USA", 9.9), ("FRA", 7.4), ("NLD", 7.0), ("CHN", 6.1), ("POL", 5.7)],
            "top_exports": ["Vehicles", "Machinery", "Chemicals", "Pharmaceuticals", "Electronics"],
            "top_imports": ["Energy", "Electronics", "Vehicles", "Chemicals", "Metals"]},
    "JPN": {"exports": 717, "imports": 786, "year": 2023, "src": "MOF Japan",
            "partners": [("USA", 20.1), ("CHN", 17.6), ("KOR", 6.6), ("TWN", 6.0), ("HKG", 4.4)],
            "top_exports": ["Vehicles", "Machinery", "Semiconducters & equipment", "Steel", "Chemicals"],
            "top_imports": ["Crude petroleum", "LNG", "Coal", "Electronics", "Pharmaceuticals"]},
    "GBR": {"exports": 521, "imports": 704, "year": 2023, "src": "ONS",
            "partners": [("USA", 14.6), ("DEU", 8.7), ("NLD", 8.0), ("FRA", 6.5), ("IRL", 6.0)],
            "top_exports": ["Machinery", "Vehicles", "Pharmaceuticals", "Gold", "Crude petroleum"],
            "top_imports": ["Vehicles", "Machinery", "Energy", "Electronics", "Food"]},
    "FRA": {"exports": 648, "imports": 780, "year": 2023, "src": "DGDDI",
            "partners": [("DEU", 13.5), ("ITA", 8.5), ("USA", 8.3), ("BEL", 7.9), ("ESP", 7.7)],
            "top_exports": ["Aircraft", "Vehicles", "Pharmaceuticals", "Cosmetics", "Wine & spirits"],
            "top_imports": ["Energy", "Vehicles", "Machinery", "Electronics", "Chemicals"]},
    "IND": {"exports": 432, "imports": 673, "year": 2023, "src": "DGCI&S",
            "partners": [("USA", 17.7), ("ARE", 7.0), ("NLD", 4.7), ("CHN", 3.5), ("SGP", 3.3)],
            "top_exports": ["Refined petroleum", "Pharmaceuticals", "Gems & jewellery", "IT services", "Rice"],
            "top_imports": ["Crude petroleum", "Gold", "Electronics", "Coal", "Machinery"]},
    "RUS": {"exports": 425, "imports": 285, "year": 2023, "src": "FCS (est.)",
            "partners": [("CHN", 30.0), ("IND", 17.0), ("TUR", 9.0), ("BLR", 5.0), ("KAZ", 4.0)],
            "top_exports": ["Crude petroleum", "Refined petroleum", "Natural gas", "Coal", "Fertilizers"],
            "top_imports": ["Machinery", "Electronics", "Vehicles", "Pharmaceuticals", "Consumer goods"]},
    "KOR": {"exports": 632, "imports": 642, "year": 2023, "src": "KITA",
            "partners": [("CHN", 19.7), ("USA", 18.3), ("VNM", 8.5), ("JPN", 4.6), ("HKG", 4.0)],
            "top_exports": ["Semiconductors", "Vehicles", "Refined petroleum", "Ships", "Displays"],
            "top_imports": ["Crude petroleum", "Semiconductor equipment", "LNG", "Coal", "Electronics"]},
    "BRA": {"exports": 340, "imports": 241, "year": 2023, "src": "SECEX",
            "partners": [("CHN", 30.7), ("USA", 11.0), ("ARG", 4.9), ("NLD", 3.4), ("ESP", 2.6)],
            "top_exports": ["Soybeans", "Crude petroleum", "Iron ore", "Corn", "Beef"],
            "top_imports": ["Refined petroleum", "Fertilizers", "Electronics", "Vehicles", "Pharmaceuticals"]},
    "SAU": {"exports": 322, "imports": 190, "year": 2023, "src": "GASTAT",
            "partners": [("CHN", 16.2), ("IND", 10.6), ("JPN", 9.6), ("KOR", 8.9), ("USA", 4.9)],
            "top_exports": ["Crude petroleum", "Refined petroleum", "Petrochemicals", "Plastics", "Fertilizers"],
            "top_imports": ["Machinery", "Vehicles", "Electronics", "Food", "Pharmaceuticals"]},
    "TUR": {"exports": 256, "imports": 362, "year": 2023, "src": "TÜİK",
            "partners": [("DEU", 8.3), ("USA", 5.8), ("IRQ", 5.0), ("GBR", 4.8), ("ITA", 4.7)],
            "top_exports": ["Vehicles", "Machinery", "Steel", "Textiles", "Electronics"],
            "top_imports": ["Energy", "Gold", "Machinery", "Chemicals", "Electronics"]},
    "IRN": {"exports": 95, "imports": 68, "year": 2023, "src": "IRICA (est.)",
            "partners": [("CHN", 30.0), ("IRQ", 15.0), ("TUR", 10.0), ("ARE", 9.0), ("AFG", 4.0)],
            "top_exports": ["Crude petroleum (sanctioned flows)", "Petrochemicals", "Pistachios", "Steel", "Carpets"],
            "top_imports": ["Machinery", "Grains", "Electronics", "Vehicles parts", "Pharmaceuticals"]},
    "ARE": {"exports": 488, "imports": 425, "year": 2023, "src": "FCSC",
            "partners": [("IND", 13.5), ("CHN", 11.5), ("SAU", 6.5), ("IRQ", 5.0), ("CHE", 4.5)],
            "top_exports": ["Crude petroleum", "Gold (re-export)", "Refined petroleum", "Aluminium", "Electronics (re-export)"],
            "top_imports": ["Gold", "Electronics", "Vehicles", "Machinery", "Diamonds"]},
    "AUS": {"exports": 371, "imports": 309, "year": 2023, "src": "ABS",
            "partners": [("CHN", 32.5), ("JPN", 14.1), ("KOR", 6.8), ("IND", 5.5), ("USA", 4.9)],
            "top_exports": ["Iron ore", "Coal", "LNG", "Gold", "Lithium"],
            "top_imports": ["Refined petroleum", "Vehicles", "Machinery", "Electronics", "Pharmaceuticals"]},
    "ZAF": {"exports": 111, "imports": 124, "year": 2023, "src": "SARS",
            "partners": [("CHN", 11.5), ("USA", 8.5), ("DEU", 8.0), ("JPN", 5.5), ("IND", 5.0)],
            "top_exports": ["Platinum", "Gold", "Coal", "Iron ore", "Vehicles"],
            "top_imports": ["Refined petroleum", "Machinery", "Electronics", "Vehicles", "Pharmaceuticals"]},
    "NGA": {"exports": 63, "imports": 52, "year": 2023, "src": "NBS",
            "partners": [("IND", 12.0), ("ESP", 10.0), ("NLD", 9.0), ("FRA", 7.0), ("USA", 6.0)],
            "top_exports": ["Crude petroleum", "LNG", "Cocoa", "Fertilizers", "Sesame"],
            "top_imports": ["Refined petroleum", "Machinery", "Vehicles", "Wheat", "Pharmaceuticals"]},
    "MEX": {"exports": 593, "imports": 598, "year": 2023, "src": "INEGI",
            "partners": [("USA", 83.0), ("CAN", 2.8), ("CHN", 1.7), ("DEU", 1.4), ("JPN", 0.9)],
            "top_exports": ["Vehicles", "Electronics", "Machinery", "Crude petroleum", "Medical devices"],
            "top_imports": ["Electronics", "Machinery", "Refined petroleum", "Vehicle parts", "Plastics"]},
    "IDN": {"exports": 259, "imports": 222, "year": 2023, "src": "BPS",
            "partners": [("CHN", 25.0), ("USA", 9.5), ("JPN", 8.0), ("IND", 7.5), ("SGP", 5.5)],
            "top_exports": ["Coal", "Palm oil", "Nickel products", "LNG", "Textiles"],
            "top_imports": ["Machinery", "Refined petroleum", "Electronics", "Steel", "Chemicals"]},
    "EGY": {"exports": 39, "imports": 73, "year": 2023, "src": "CAPMAS",
            "partners": [("TUR", 8.0), ("SAU", 7.0), ("ITA", 6.5), ("USA", 6.0), ("ARE", 5.5)],
            "top_exports": ["Refined petroleum", "LNG", "Gold", "Fertilizers", "Textiles"],
            "top_imports": ["Wheat", "Refined petroleum", "Machinery", "Vehicles", "Pharmaceuticals"]},
    "UKR": {"exports": 36, "imports": 63, "year": 2023, "src": "Customs (wartime)",
            "partners": [("POL", 11.5), ("ROU", 9.5), ("CHN", 8.0), ("TUR", 7.5), ("DEU", 6.5)],
            "top_exports": ["Corn", "Sunflower oil", "Wheat", "Iron ore", "Steel"],
            "top_imports": ["Refined petroleum", "Vehicles", "Weapons & aid flows", "Machinery", "Pharmaceuticals"]},
}

WORLD_TRADE = {
    "total_merchandise_exports": 23800, "year": 2023, "src": "WTO",
    "top_traders": ["CHN", "USA", "DEU", "NLD", "JPN"],
    "chokepoints": [
        ("Strait of Hormuz", "~21% of global petroleum liquids"),
        ("Strait of Malacca", "~30% of global seaborne trade"),
        ("Suez Canal", "~12% of global trade volume"),
        ("Bab-el-Mandeb", "~9% of seaborne petroleum"),
        ("Panama Canal", "~5% of global maritime trade"),
        ("Taiwan Strait", "~40% of the global container fleet transits yearly"),
    ],
}

# iso3 → {resources: [...], production: [(what, figure, unit, year)], industry: [...]}
RESOURCES = {
    "USA": {"resources": ["Oil & gas", "Coal", "Copper", "Rare earths (Mountain Pass)", "Timber"],
            "production": [("Crude oil", 12.9, "Mb/d", 2023), ("Natural gas", 1035, "bcm", 2023), ("Coal", 522, "Mt", 2023)],
            "industry": ["Technology & software", "Aerospace & defense", "Pharma", "Autos", "Agriculture"]},
    "CHN": {"resources": ["Coal", "Rare earths (~60% global)", "Iron", "Lithium processing", "Hydropower"],
            "production": [("Coal", 4660, "Mt", 2023), ("Steel", 1019, "Mt", 2023), ("Rare earths", 240, "kt", 2023)],
            "industry": ["Electronics & EVs", "Steel & shipbuilding", "Solar & batteries", "Textiles", "Machinery"]},
    "RUS": {"resources": ["Natural gas (#1 reserves)", "Oil", "Coal", "Nickel & palladium", "Timber"],
            "production": [("Crude oil", 10.1, "Mb/d", 2023), ("Natural gas", 586, "bcm", 2023), ("Wheat", 92, "Mt", 2023)],
            "industry": ["Hydrocarbons", "Defense", "Metals & mining", "Grain", "Nuclear tech"]},
    "SAU": {"resources": ["Oil (~17% world reserves)", "Natural gas", "Phosphates", "Gold"],
            "production": [("Crude oil", 9.0, "Mb/d", 2023), ("Refined products", 2.9, "Mb/d", 2023)],
            "industry": ["Hydrocarbons", "Petrochemicals", "NEOM/giga-projects", "Mining (Ma'aden)"]},
    "IRN": {"resources": ["Natural gas (#2 reserves)", "Oil", "Copper", "Zinc", "Iron"],
            "production": [("Crude oil", 3.1, "Mb/d", 2023), ("Natural gas", 259, "bcm", 2023)],
            "industry": ["Hydrocarbons", "Petrochemicals", "Steel", "Automotive", "Carpets & agrifood"]},
    "AUS": {"resources": ["Iron ore (#1 exporter)", "Coal", "Lithium (#1 producer)", "Gold", "Uranium"],
            "production": [("Iron ore", 960, "Mt", 2023), ("Lithium", 86, "kt LCE", 2023), ("Coal", 443, "Mt", 2023)],
            "industry": ["Mining", "Agriculture", "LNG", "Education exports", "Finance"]},
    "COD": {"resources": ["Cobalt (~70% global)", "Copper", "Coltan", "Diamonds", "Hydropower potential"],
            "production": [("Cobalt", 170, "kt", 2023), ("Copper", 2.8, "Mt", 2023)],
            "industry": ["Mining", "Subsistence agriculture"]},
    "CHL": {"resources": ["Copper (#1 producer)", "Lithium (#2)", "Molybdenum"],
            "production": [("Copper", 5.3, "Mt", 2023), ("Lithium", 44, "kt LCE", 2023)],
            "industry": ["Mining", "Agriculture & wine", "Fisheries", "Forestry"]},
    "UKR": {"resources": ["Iron ore", "Titanium", "Lithium (undeveloped)", "Black-earth farmland", "Gas (contested)"],
            "production": [("Wheat", 22, "Mt", 2023), ("Corn", 29, "Mt", 2023)],
            "industry": ["Agriculture", "Steel (war-degraded)", "IT services", "Defense tech (drones)"]},
    "IND": {"resources": ["Coal", "Iron ore", "Bauxite", "Thorium", "Arable land"],
            "production": [("Coal", 997, "Mt", 2023), ("Steel", 140, "Mt", 2023), ("Rice", 135, "Mt", 2023)],
            "industry": ["IT & services", "Pharma (generics #1)", "Textiles", "Autos", "Space (ISRO)"]},
    "BRA": {"resources": ["Iron ore", "Oil (pre-salt)", "Niobium (~90% global)", "Farmland", "Fresh water"],
            "production": [("Iron ore", 440, "Mt", 2023), ("Soybeans", 155, "Mt", 2023), ("Crude oil", 3.4, "Mb/d", 2023)],
            "industry": ["Agribusiness", "Mining", "Aerospace (Embraer)", "Energy", "Autos"]},
    "NOR": {"resources": ["Oil & gas", "Hydropower", "Fish", "Minerals (seabed, contested)"],
            "production": [("Natural gas", 116, "bcm", 2023), ("Crude oil", 1.8, "Mb/d", 2023)],
            "industry": ["Hydrocarbons", "Maritime & shipping", "Aquaculture", "Sovereign wealth (GPFG)"]},
    "QAT": {"resources": ["Natural gas (North Field)", "Oil"],
            "production": [("LNG exports", 108, "bcm", 2023)],
            "industry": ["LNG", "Petrochemicals", "Finance", "Aviation (Qatar Airways)"]},
    "KAZ": {"resources": ["Uranium (#1 producer)", "Oil", "Chromium", "Coal", "Wheat"],
            "production": [("Uranium", 21, "kt", 2023), ("Crude oil", 1.9, "Mb/d", 2023)],
            "industry": ["Mining & metallurgy", "Hydrocarbons", "Grain", "Transit (Middle Corridor)"]},
    "TWN": {"resources": ["Limited natural resources — strategic asset is fabrication capacity"],
            "production": [("Semiconductor foundry share", 60, "% global (TSMC ~90% advanced)", 2023)],
            "industry": ["Semiconductors", "Electronics", "Precision machinery", "Petrochemicals"]},
}


def trade_for(iso3):
    return TRADE.get(iso3)


def resources_for(iso3):
    return RESOURCES.get(iso3)
