"""v4 §2.3 — build vendored country-boundary modules from Natural Earth.

Converts Natural Earth admin-0 GeoJSON (public domain) into compact,
buildless ES modules under frontend/src/data/:

    boundaries50m.js   — far-zoom LOD (full-globe view)
    boundaries10m.js   — near-zoom LOD (accurate coastlines up close)

Rings are quantized to 1e-3 degrees (~110 m) and delta-encoded with the
Google polyline algorithm (decoder in boundaryCodec.js), which keeps the
10m dataset (~550k points) small enough to vendor. The generated files are
checked in so the app stays zero-install; re-run this script only to
refresh the datasets:

    curl -L -o ne_10m.json https://raw.githubusercontent.com/nvkelso/\
natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson
    curl -L -o ne_50m.json https://raw.githubusercontent.com/nvkelso/\
natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson
    python scripts/build_boundaries.py ne_50m.json ne_10m.json

Natural Earth data is public domain (naturalearthdata.com); credited on
the sources & credits page (v4 §22).
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "frontend" / "src" / "data"

# Natural Earth ADM0_A3 codes that differ from the IDs used in our
# countries table (v4 §5.2 keeps de facto states in the table, status-flagged)
CODE_MAP = {"KOS": "XKX", "PSX": "PSE", "SDS": "SSD"}


def _encode_ring(ring, quant=1000):
    """Google polyline delta encoding over quantized (lon, lat) pairs."""
    out = []
    prev_lon = prev_lat = 0
    last = None
    for lon, lat in ring:
        qlon, qlat = round(lon * quant), round(lat * quant)
        if (qlon, qlat) == last:
            continue
        last = (qlon, qlat)
        for delta in (qlon - prev_lon, qlat - prev_lat):
            v = ~(delta << 1) if delta < 0 else (delta << 1)
            while v >= 0x20:
                out.append(chr((0x20 | (v & 0x1F)) + 63))
                v >>= 5
            out.append(chr(v + 63))
        prev_lon, prev_lat = qlon, qlat
    return "".join(out)


def _rings(geometry):
    if geometry["type"] == "Polygon":
        yield geometry["coordinates"][0]
        for hole in geometry["coordinates"][1:]:
            yield hole
    elif geometry["type"] == "MultiPolygon":
        for poly in geometry["coordinates"]:
            for ring in poly:
                yield ring


def build(src_path: str, out_name: str, export: str, min_ring_points: int = 4):
    data = json.loads(Path(src_path).read_text(encoding="utf-8"))
    countries = []
    for feat in data["features"]:
        props = feat["properties"]
        code = props.get("ADM0_A3") or props.get("ISO_A3") or ""
        iso = props.get("ISO_A3_EH") or props.get("ISO_A3") or ""
        if iso in ("-99", "", None):
            iso = code
        iso = CODE_MAP.get(code, CODE_MAP.get(iso, iso))
        name = props.get("NAME_LONG") or props.get("NAME") or iso
        rings, bbox = [], [180.0, 90.0, -180.0, -90.0]
        for ring in _rings(feat["geometry"]):
            if len(ring) < min_ring_points:
                continue
            enc = _encode_ring(ring)
            if enc:
                rings.append(enc)
                for lon, lat in ring:
                    bbox[0] = min(bbox[0], lon); bbox[1] = min(bbox[1], lat)
                    bbox[2] = max(bbox[2], lon); bbox[3] = max(bbox[3], lat)
        if rings:
            countries.append({"i": iso, "n": name,
                              "b": [round(v, 2) for v in bbox], "r": rings})
    countries.sort(key=lambda c: c["i"])
    # json.dumps already escapes backslashes/quotes correctly for a JS
    # literal — do NOT escape again (that corrupts polyline chunks
    # containing chr(92) and makes rings drift)
    body = json.dumps(countries, ensure_ascii=False, separators=(",", ":"))
    js = (
        "// GENERATED by scripts/build_boundaries.py — do not edit by hand.\n"
        "// Source: Natural Earth admin-0 countries (public domain,\n"
        "// naturalearthdata.com). Rings are polyline-encoded at 1e-3 deg;\n"
        "// decode with frontend/src/data/boundaryCodec.js.\n"
        f"export const {export} = {body};\n")
    out = OUT_DIR / out_name
    out.write_text(js, encoding="utf-8")
    pts = sum(len(r) for c in countries for r in c["r"])
    print(f"{out_name}: {len(countries)} countries, ~{pts // 2} encoded chars,"
          f" {out.stat().st_size / 1e6:.2f} MB")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: build_boundaries.py <ne_50m.json> <ne_10m.json>")
    build(sys.argv[1], "boundaries50m.js", "BOUNDARIES_50M_ENC")
    build(sys.argv[2], "boundaries10m.js", "BOUNDARIES_10M_ENC")
