#!/usr/bin/env python3
"""V8.4 — real historical WORLD boundary geometry (1945 → present).

The owner: border history should "go back at least until 1950 … switch to real
data the second it's available." This vendors ACTUAL historical country polygons
(not estimates) from the community `historical-basemaps` project (aourednik,
CC-BY-SA) — the whole world's borders at a set of epoch years — so the time
capsule can redraw the map with the borders of that era: the USSR as one polity
pre-1991, unified Yugoslavia, colonial-era Africa, and so on.

Fetches world_{year}.geojson for a handful of epochs, simplifies + polyline-
encodes each country's rings the SAME way as the live boundaries
(boundaryCodec.js), and emits one committed artifact:

  frontend/src/data/historicalBoundaries.js  → HISTORICAL_EPOCHS
      = [{ year, countries: [{ n: name, r: [encoded rings] }] }, …] (ascending)

Pure stdlib. Build-time only; the output is committed and served. Present-day
borders stay the live vector set — this layer is the OVERLAY for past epochs.

Usage:  python scripts/build_historical_boundaries.py
"""
import json
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_admin_atlas import REPO, _dp, _rings_of, encode_ring, MIN_RING_PTS

# epochs that historical-basemaps actually publishes AND that bracket the big
# 20th-century border changes (post-WWII empires → decolonisation → the USSR /
# Yugoslavia / Czechoslovakia breakups → present).
# v8.6 — a much denser epoch set: the colonial-peak / interwar years (1880 →
# 1938) now sit beside the postwar → present ones, so the time scrubber redraws
# Austria-Hungary and the Ottoman Empire (pre-1914), the post-WWI settlement
# (1920), colonial-peak Africa, and the USSR/Yugoslavia as single polities. All
# confirmed published by historical-basemaps; a missing/blocked one is skipped.
EPOCHS = [1880, 1900, 1914, 1920, 1930, 1938, 1945, 1960, 1994, 2000, 2010]
SRC = ("https://raw.githubusercontent.com/aourednik/historical-basemaps/master/"
       "geojson/world_{year}.geojson")
HTOL = 0.06   # overlay-only, simplify harder than the live borders to stay small


def fetch(year):
    cache = REPO / "scripts" / f"_hist_world_{year}.geojson"
    if cache.exists():
        return json.loads(cache.read_text())
    print(f"fetching historical world_{year} …", file=sys.stderr)
    with urllib.request.urlopen(SRC.format(year=year), timeout=90) as r:
        data = r.read()
    cache.write_bytes(data)
    return json.loads(data)


def encode_country(geom):
    rings = []
    for ring in _rings_of(geom):
        pts = [(c[0], c[1]) for c in ring if len(c) >= 2]
        if len(pts) < MIN_RING_PTS:
            continue
        simp = _dp(pts, HTOL)
        if len(simp) < 3:
            continue
        flat = []
        for x, y in simp:
            flat.append(x); flat.append(y)
        rings.append(encode_ring(flat))
    return rings


def main():
    epochs_out = []
    for year in EPOCHS:
        try:
            gj = fetch(year)
        except Exception as e:  # noqa: BLE001 — a missing epoch must not abort
            print(f"world_{year}: SKIPPED ({type(e).__name__}: {e})", file=sys.stderr)
            continue
        countries = []
        for f in gj.get("features", []):
            p = f.get("properties", {})
            geom = f.get("geometry")
            name = (p.get("NAME") or p.get("name") or "").strip()
            if not geom or not name:
                continue
            rings = encode_country(geom)
            if rings:
                countries.append({"n": name, "r": rings})
        epochs_out.append({"year": year, "countries": countries})
        print(f"world_{year}: {len(countries)} polities", file=sys.stderr)

    fe = REPO / "frontend" / "src" / "data" / "historicalBoundaries.js"
    with open(fe, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by scripts/build_historical_boundaries.py — DO NOT EDIT.\n")
        fh.write("// V8.4 — real historical world boundaries (historical-basemaps,\n")
        fh.write("// CC-BY-SA), polyline-encoded. The time capsule overlays the epoch\n")
        fh.write("// whose year is <= the as_of date. Ascending by year.\n")
        fh.write("export const HISTORICAL_EPOCHS = ")
        json.dump(epochs_out, fh, separators=(",", ":"), ensure_ascii=False)
        fh.write(";\n")
    print(f"wrote {fe} ({fe.stat().st_size // 1024} KB, {len(epochs_out)} epochs)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
